import type { VocabularyGloss } from "./glosses";

export const cultureGlosses: VocabularyGloss[] = [
  ["choir", "coro", "a group of people who sing together"],
  ["composer", "compositor", "a person who writes music"],
  ["conductor", "director de orquesta", "a person who directs an orchestra or choir"],
  ["guitarist", "guitarrista", "a person who plays the guitar"],
  ["orchestra", "orquesta", "a large group of musicians who play different instruments together"],
  ["beat", "pulso / ritmo", "the regular pattern of strong and weak sounds in music"],
  ["lyrics", "letra de una canción", "the words of a song"],
  ["rhythm", "ritmo", "a regular pattern of sounds or movements"],
  ["tune", "melodía", "a series of musical notes that form a recognisable melody"],
  ["musical instrument", "instrumento musical", "an object used to produce music"],
  ["cello", "violonchelo", "a large stringed instrument played while sitting down"],
  ["violin", "violín", "a small stringed instrument played with a bow"],
  ["concert", "concierto", "a live performance of music in front of an audience"],
  ["headphones", "auriculares", "a device worn over or in the ears for listening privately to audio"],
  ["sing in tune", "cantar afinado", "to sing the correct musical notes"],
  ["sing solo", "cantar solo", "to sing alone rather than as part of a group"],
  ["get to a high standard", "alcanzar un nivel alto", "to reach a very good level of ability or quality"],
  ["make a special trip", "hacer un viaje expresamente", "to travel somewhere specifically for one particular purpose"],
  ["have something playing", "tener música sonando", "to have music or another recording playing in the background"],
  ["have headphones on", "llevar los auriculares puestos", "to be wearing headphones"],
  ["album", "álbum", "a collection of music tracks released together"],
  ["track", "pista / canción grabada", "one recorded song or piece of music on an album"],
  ["cover version", "versión de una canción de otro artista", "a new recording of a song originally performed by someone else"],
  ["arrangement", "arreglo musical", "a particular version of a piece of music adapted for certain voices or instruments"],
  ["repertoire", "repertorio", "the collection of pieces that a performer or group can perform"],
  ["fan", "fan / seguidor", "a person who strongly likes and supports a performer, team or activity"],
  ["catchy tune", "melodía pegadiza", "a melody that is easy to remember"],
  ["harmony", "armonía", "a pleasing combination of musical notes played or sung together"],
  ["lead guitar", "guitarra principal", "the guitar part that usually plays the main melodic or solo lines"],
  ["guitar solo", "solo de guitarra", "a section of music in which one guitar plays alone or is especially prominent"],
  ["drums", "batería", "a set of percussion instruments played by a drummer"],
  ["chamber song", "canción de cámara", "a song written for a small number of performers in an intimate classical setting"],
  ["duet", "dúo", "a piece of music performed by two people"],
  ["distinctive style", "estilo distintivo", "a recognisable and characteristic way of performing or creating music"],
  ["rock", "rock", "a popular style of music with a strong beat, often using electric guitars"],
  ["pop", "pop", "popular music designed for a wide audience, often with short memorable songs"],
  ["classical music", "música clásica", "music written in established artistic traditions, often for orchestras or formal ensembles"],
  ["world music", "músicas del mundo", "music from traditional or non-Western cultural styles from around the world"],
  ["jazz", "jazz", "a music style characterised by rhythm, improvisation and distinctive harmonies"],
  ["folk", "folk / música tradicional", "traditional music associated with a particular community or culture"],
  ["rock ’n’ roll", "rock and roll", "an energetic style of popular music that developed in the 1950s"],
  ["country and western", "música country", "a style of American popular music associated with rural traditions"],
  ["heavy metal", "heavy metal", "a loud and powerful style of rock music with heavily amplified guitars"],
  ["rumba", "rumba", "a lively style of music and dance with Latin and Afro-Cuban origins"],
  ["tango", "tango", "a dramatic partner dance and musical style originating in the Río de la Plata region"],
  ["bang", "golpe / estallido; golpear", "a sudden loud noise, or to make such a noise by hitting something"],
  ["bark", "ladrido; ladrar", "the short loud sound made by a dog, or to make that sound"],
  ["smash", "estruendo al romperse; romper con fuerza", "a loud breaking sound, or to break something violently"],
  ["sneeze", "estornudo; estornudar", "a sudden uncontrolled burst of air through the nose and mouth, or to produce it"],
  ["snore", "ronquido; roncar", "a rough breathing sound made while sleeping, or to make that sound"],
  ["splash", "chapoteo / salpicadura; salpicar", "the sound or movement of liquid being scattered, or to scatter liquid"],
  ["tap", "golpecito; dar golpecitos", "a light quick hit, or to hit something gently"],
  ["whistle", "silbido; silbar", "a high sound made by blowing air through the lips, or to make that sound"],

  ["go skating", "ir a patinar", "to do skating as a leisure or sporting activity"],
  ["go cycling", "ir en bici", "to ride a bicycle as an activity"],
  ["go jogging", "salir a trotar", "to run slowly for exercise"],
  ["go walking", "ir a caminar", "to walk for exercise or leisure"],
  ["go swimming", "ir a nadar", "to swim as a leisure or sporting activity"],
  ["go climbing", "ir a escalar", "to climb rocks or mountains as a sport"],
  ["go skateboarding", "hacer skate", "to ride a skateboard as an activity"],
  ["go skiing", "ir a esquiar", "to travel over snow on skis"],
  ["go diving", "ir a bucear", "to swim underwater, often using special equipment"],
  ["go snorkelling", "hacer snorkel", "to swim near the surface while breathing through a snorkel"],
  ["go sailing", "salir a navegar", "to travel or compete in a sailing boat"],
  ["go snowboarding", "hacer snowboard", "to travel over snow on a snowboard"],
  ["go hiking", "ir de senderismo", "to take long walks in the countryside or mountains"],
  ["go surfing", "hacer surf", "to ride waves on a surfboard"],
  ["play volleyball", "jugar al voleibol", "to take part in the sport of volleyball"],
  ["play squash", "jugar al squash", "to take part in the sport of squash"],
  ["play rugby", "jugar al rugby", "to take part in the sport of rugby"],
  ["play badminton", "jugar al bádminton", "to take part in the sport of badminton"],
  ["play hockey", "jugar al hockey", "to take part in the sport of hockey"],
  ["play football", "jugar al fútbol", "to take part in the sport of football"],
  ["play table tennis", "jugar al tenis de mesa", "to take part in the sport of table tennis"],
  ["play baseball", "jugar al béisbol", "to take part in the sport of baseball"],
  ["play ice hockey", "jugar al hockey sobre hielo", "to take part in the sport of ice hockey"],
  ["do judo", "hacer judo", "to practise the martial art of judo"],
  ["do yoga", "hacer yoga", "to practise yoga"],
  ["do aerobics", "hacer aeróbic", "to do rhythmic exercise designed to improve fitness"],
  ["do athletics", "hacer atletismo", "to take part in athletics events"],
  ["do gymnastics", "hacer gimnasia", "to practise gymnastics"],
  ["do martial arts", "practicar artes marciales", "to practise fighting systems such as karate or judo"],
  ["course", "campo / recorrido (golf)", "the area of land where a sport such as golf is played"],
  ["court", "pista (tenis, squash)", "a marked area where sports such as tennis, squash or basketball are played"],
  ["pitch", "campo de juego", "an outdoor field used for sports such as football or rugby"],
  ["track", "pista de atletismo", "a specially prepared path used for running races"],
  ["bat", "bate", "a piece of sports equipment used to hit a ball in games such as baseball or cricket"],
  ["clubs", "palos de golf", "sticks used for hitting a golf ball"],
  ["racket", "raqueta", "a handled frame with strings used to hit a ball or shuttlecock"],
  ["stick", "stick / palo de hockey", "a long piece of sports equipment used to hit a ball or puck in hockey"],
  ["run → runner", "correr → corredor", "to move quickly on foot → a person who runs"],
  ["jog → jogger", "trotar → corredor de jogging", "to run slowly for exercise → a person who jogs"],
  ["walk → walker", "caminar → caminante", "to move on foot at a normal pace → a person who walks"],
  ["swim → swimmer", "nadar → nadador", "to move through water using the body → a person who swims"],
  ["climb → climber", "escalar → escalador", "to move up a steep surface → a person who climbs"],
  ["skate → skater", "patinar → patinador", "to move using skates → a person who skates"],
  ["ski → skier", "esquiar → esquiador", "to move over snow on skis → a person who skis"],
  ["dive → diver", "bucear → buceador", "to go underwater or enter water head first → a person who dives"],
  ["cycle → cyclist", "ir en bici → ciclista", "to ride a bicycle → a person who rides a bicycle"],
  ["gymnastics → gymnast", "gimnasia → gimnasta", "a sport involving controlled physical movements → a person who does gymnastics"],
  ["athletics → athlete", "atletismo → atleta", "sports involving running, jumping and throwing → a person who competes in sport"],
  ["football → footballer", "fútbol → futbolista", "the sport of football → a person who plays football"],
  ["sport + player", "volleyball player, rugby player, etc.", "a productive pattern for naming someone who plays a particular sport"],
  ["varied", "variado", "including many different kinds or activities"],
  ["relaxing", "relajante", "helping you feel calm and less tense"],
  ["demanding", "exigente", "requiring a lot of effort, skill or energy"],
  ["exciting", "emocionante", "making you feel interested, enthusiastic or eager"],
  ["challenging", "desafiante", "difficult in an interesting way that tests your ability"],
  ["satisfying", "satisfactorio", "giving a feeling of achievement or pleasure"],
  ["win a race / semi-final / cup / medal / trophy", "ganar una competición o premio", "to be the successful competitor in a race or semi-final / to obtain a cup, medal or trophy by succeeding"],
  ["beat a team / opponent / rival", "vencer a una persona o equipo", "to defeat another team, opponent or rival"],
  ["beat a record / time", "superar un récord / marca", "to achieve a better result than an existing record or time"],
  ["beat someone at a game", "ganar a alguien en un juego", "to defeat someone in a particular game"],
  ["run a business", "dirigir un negocio", "to manage and be responsible for a business"],
  ["tears run down ...", "las lágrimas corren por...", "to move in a continuous line down a surface, as tears do on a face"],
  ["a machine runs", "una máquina funciona", "a machine operates or works"],
  ["run a check", "hacer una comprobación", "to perform a check or examination"],
  ["a bus runs", "un autobús circula", "a bus operates on a route or according to a timetable"],
  ["run someone down", "criticar a alguien", "to criticise someone unfairly or repeatedly"],
  ["run in the family", "ser hereditario / común en la familia", "to be a characteristic shared by several members of a family"],
  ["run into someone", "encontrarse con alguien por casualidad", "to meet someone unexpectedly"],
  ["run out of", "quedarse sin", "to use all of something so that none is left"],
  ["run up against", "toparse con un obstáculo / problema", "to encounter a difficulty or obstacle"],
  ["run on petrol", "funcionar con gasolina", "to use petrol as the fuel that makes a machine or vehicle work"],
  ["run over someone/something", "atropellar / pasar por encima", "to hit and pass over someone or something with a vehicle"],
  ["run through something", "repasar rápidamente", "to review or practise something quickly"],
  ["run into a tree", "chocar contra un árbol", "to collide with a tree while moving"],

  ["eat out with friends", "comer fuera con amigos", "to have a meal in a restaurant or café with friends"],
  ["go to a party", "ir a una fiesta", "to attend a social celebration"],
  ["cook with friends", "cocinar con amigos", "to prepare food together with friends"],
  ["have a takeaway", "pedir / tomar comida para llevar", "to eat food prepared by a restaurant to be eaten elsewhere"],
  ["play music", "tocar música", "to perform music using an instrument or instruments"],
  ["cook for myself", "cocinar para mí", "to prepare your own meals"],
  ["watch sport on TV", "ver deporte en la tele", "to watch televised sports"],
  ["paint and draw", "pintar y dibujar", "to create pictures using paint and drawing materials"],
  ["collect old postcards", "coleccionar postales antiguas", "to gather and keep old postcards as a hobby"],
  ["go to junk shops", "ir a tiendas de segunda mano / objetos usados", "to visit shops selling used, unusual or inexpensive objects"],
  ["go clubbing", "salir de discotecas", "to go to nightclubs for dancing and entertainment"],
  ["go to the cinema", "ir al cine", "to go to a cinema to watch a film"],
  ["go to the beach", "ir a la playa", "to spend time at the seaside"],
  ["watch DVDs", "ver DVDs", "to watch films or programmes recorded on DVDs"],
  ["play online games", "jugar online", "to play computer or video games over the internet"],
  ["read a book", "leer un libro", "to read a written work in book form"],
  ["have a barbecue / coffee / quiet night in", "hacer una barbacoa / tomar un café / pasar una noche tranquila en casa", "to organise or eat a barbecue / to drink coffee / to spend a calm evening at home"],
  ["have friends round", "invitar amigos a casa", "to invite friends to your home"],
  ["watch a film / match / play / TV", "ver una película / partido / obra / TV", "to look at a film / sports match / theatrical performance / television for a period of time"],
  ["play cards / games", "jugar a las cartas / juegos", "to take part in card games / to take part in games"],
  ["go shopping", "ir de compras", "to visit shops in order to buy things"],
  ["go to a club / concert / restaurant / theatre", "ir a un club / concierto / restaurante / teatro", "to visit a nightclub / live music event / restaurant / theatre"],
  ["go for a coffee / drive / walk", "ir a tomar un café / dar una vuelta en coche / pasear", "to go out in order to drink coffee / travel by car for pleasure / walk for pleasure"],
  ["jigsaw", "puzle", "a puzzle made from many pieces that fit together to form a picture"],
  ["crossword", "crucigrama", "a word puzzle in which answers are written into crossing horizontal and vertical spaces"],
  ["computer game", "videojuego", "a game played using a computer or electronic device"],
  ["dominoes", "dominó", "a game played with small rectangular pieces marked with dots"],
  ["scrabble", "Scrabble", "a board game in which players form words from letter tiles"],
  ["backgammon", "backgammon", "a board game for two players using pieces moved according to dice"],
  ["chess", "ajedrez", "a strategic board game for two players"],
  ["sudoku", "sudoku", "a number puzzle in which digits are placed in a grid according to rules"],
  ["board game", "juego de mesa", "a game played on a board, usually with pieces or cards"],
  ["snakes and ladders", "serpientes y escaleras", "a simple board game in which players move up ladders and down snakes"],
  ["shell", "concha", "the hard outer covering of some sea animals"],
  ["stamp", "sello", "a small piece of printed paper attached to mail to show postage has been paid"],
  ["play games", "jugar a juegos", "to take part in games"],
  ["do puzzles", "hacer puzles / pasatiempos", "to solve puzzles"],
  ["collect objects", "coleccionar objetos", "to gather and keep objects as a hobby"],
  ["take after", "parecerse a un familiar", "to resemble an older member of your family in appearance or character"],
  ["take off a few days", "tomarse unos días libres", "to have several days away from work or normal duties"],
  ["take out money", "sacar dinero", "to withdraw money, especially from a bank account"],
  ["take over a business", "hacerse con el control de un negocio", "to gain control of a business"],
  ["take to someone / something", "cogerle gusto a alguien / algo", "to begin to like someone / to begin to like or enjoy something"],
  ["take up space", "ocupar espacio", "to use or fill a particular amount of space"],
  ["take up a hobby", "empezar un hobby", "to begin doing a hobby regularly"],
  ["take on responsibility", "asumir responsabilidad / trabajo", "to accept responsibility or additional work"],
  ["point → pointless", "sentido / punto → sin sentido", "a purpose or useful reason → having no purpose or useful result"],
  ["commit → commitment", "comprometerse → compromiso", "to promise or devote yourself to something → a promise or serious responsibility"],
  ["like → unlike", "como / gustar → a diferencia de", "to enjoy or be similar to depending on use → different from"],
  ["add → addition", "añadir → adición", "to put something extra with something else → the act or result of adding"],
  ["friend → friendship", "amigo → amistad", "a person you know and like → the relationship between friends"],
  ["person → personal", "persona → personal", "an individual human being → relating to one particular person"],
  ["strong → strength", "fuerte → fortaleza", "having physical or mental power → the quality of being strong"],
  ["true → truly", "verdadero → verdaderamente", "correct or real → in a truthful, genuine or complete way"],

  ["prawns", "gambas / langostinos", "small sea animals with shells that are commonly eaten"],
  ["ginger", "jengibre", "a spicy root used to flavour food"],
  ["spices", "especias", "strongly flavoured plant substances used in cooking"],
  ["soy sauce", "salsa de soja", "a dark salty liquid made from fermented soya beans"],
  ["stir-fry", "salteado al wok", "a dish cooked quickly by frying small pieces of food while stirring them"],
  ["rice", "arroz", "small grains from a cereal plant that are cooked and eaten as food"],
  ["noodles", "fideos", "long thin strips of pasta-like food often used in Asian dishes"],
  ["spicy food", "comida picante", "food containing strong spices that create a hot taste"],
  ["chilli", "chile / guindilla", "a small hot-tasting pepper used to flavour food"],
  ["corn", "maíz", "a cereal plant whose large yellow grains are eaten as food"],
  ["tortillas", "tortillas", "thin flat breads made from maize or wheat flour"],
  ["beans", "alubias / frijoles", "edible seeds from several kinds of plants"],
  ["herbs", "hierbas aromáticas", "plants whose leaves are used to add flavour to food"],
  ["tomatoes", "tomates", "red or yellow fruits commonly used in savoury dishes"],
  ["pasta", "pasta", "food made from flour and water in shapes such as spaghetti or penne"],
  ["olives", "aceitunas", "small oval fruits often eaten or used to make oil"],
  ["pour", "verter", "to make a liquid flow from one container into another"],
  ["beat", "batir", "to mix food quickly and repeatedly, often with a fork or whisk"],
  ["chop", "picar / trocear", "to cut food into small pieces"],
  ["peel", "pelar", "to remove the outer skin of fruit or vegetables"],
  ["grate", "rallar", "to rub food against a rough surface to make small pieces"],
  ["melt", "derretir", "to change a solid into a liquid by heating it"],
  ["slice", "cortar en rodajas", "to cut food into thin flat pieces"],
  ["stir", "remover", "to move a spoon or similar object around in food or liquid to mix it"],
  ["seafood", "marisco", "sea animals such as fish and shellfish that are eaten as food"],
  ["rice dish", "plato de arroz", "a prepared meal in which rice is a main ingredient"],
  ["salad", "ensalada", "a cold dish made mainly from raw or cooked vegetables and other ingredients"],
  ["dessert", "postre", "sweet food eaten at the end of a meal"],
  ["fresh juice", "zumo natural", "juice made from recently squeezed or processed fruit"],
  ["soft drink", "refresco", "a cold non-alcoholic drink, often sweet and fizzy"],
  ["menu", "menú", "a list of food and drinks available in a restaurant"],
  ["starter", "entrante", "a small dish eaten before the main course"],
  ["main meal / main course", "plato principal", "the most important meal of the day / the principal dish in a meal"],
  ["side dish", "guarnición", "a smaller dish served with the main food"],
  ["order", "pedido", "a request for food or drink in a restaurant"],
  ["freshness", "frescura", "the quality of being recently prepared, produced or picked"],
  ["specials", "platos especiales / del día", "dishes offered by a restaurant in addition to the regular menu"],
  ["cookbook", "libro de cocina", "a book containing recipes and cooking instructions"],
  ["recipe", "receta", "instructions explaining how to prepare and cook a particular dish"],
  ["self-service", "autoservicio", "a system in which customers serve themselves rather than being served by staff"],
  ["cater for", "atender / adaptarse a las necesidades de", "to provide what a particular group of people needs or wants"],
  ["cooker", "aparato / cocina donde cocinas", "a kitchen appliance used for cooking food"],
  ["cook", "persona que cocina", "a person who prepares and cooks food"],
  ["taste", "sabor; gusto / preferencia", "the flavour of food or drink; also a person's preference for particular styles or things"],
  ["tasty", "sabroso", "having a pleasant and strong flavour"],
  ["tasteful", "de buen gusto", "showing good judgement in style or decoration"],
  ["tasteless", "insípido; de mal gusto", "having little or no flavour; also lacking good judgement or sensitivity"],
  ["good taste", "buen gusto", "good judgement about style, appearance or quality"],
  ["be more to my taste", "ser más de mi gusto", "to suit my personal preferences better"],
  ["drawing", "dibujo", "a picture made using a pencil, pen or similar tool"],
  ["watercolour", "acuarela", "a painting made using colours mixed with water"],
  ["oil painting", "pintura al óleo", "a painting made using oil-based paints"],
  ["print", "lámina / reproducción", "a picture produced by printing, or a reproduction of an artwork"],
  ["pottery", "cerámica", "objects made from clay and hardened by heat"],
  ["textiles", "textiles", "cloth and fabric, especially considered as an art or craft material"],
  ["jewellery", "joyería", "decorative objects such as rings, necklaces and bracelets"],
  ["sculpture", "escultura", "a three-dimensional work of art made from materials such as stone, metal or wood"],
  ["portrait", "retrato", "a picture or artwork representing a particular person"],
  ["still life", "bodegón / naturaleza muerta", "an artwork showing arranged objects such as fruit, flowers or household items"],
  ["landscape", "paisaje", "an artwork showing natural scenery, or the visible features of an area of land"],
  ["abstract", "abstracto", "using shapes, colours or forms rather than realistic images"],
  ["sketch", "boceto", "a quick or simple drawing showing the main features of something"],
  ["exhibition", "exposición", "a public display of art or other objects"],
  ["gallery", "galería", "a place where works of art are displayed"],
  ["studio", "estudio", "a room or workplace used by an artist"],
  ["artistic", "artístico / con habilidad artística", "connected with art or showing skill in creating art"],
  ["creative", "creativo", "able to produce original and imaginative ideas"],
  ["conventional", "convencional", "following traditional or generally accepted styles or ideas"],
  ["style", "estilo", "a particular way of doing or presenting something"],
  ["presentation", "presentación", "the way something is shown or arranged for an audience"],
  ["picturesque", "pintoresco", "visually attractive in a charming or traditional way"],
  ["realistic", "realista", "representing things in a way that looks or feels true to real life"],
  ["shade", "tono / matiz", "a particular degree or variety of a colour"],
  ["huge", "enorme", "extremely large"],
  ["effective", "eficaz", "successful in producing the intended result"],
  ["impressive", "impresionante", "causing admiration because of quality, size or skill"],

  ["chat show", "programa de entrevistas", "a television programme in which a host talks informally with guests"],
  ["comedy", "comedia", "a programme, film or play intended to make people laugh"],
  ["costume drama", "drama de época", "a film or television drama set in the past with historically styled clothing"],
  ["current affairs", "actualidad", "news and discussion about important events happening now"],
  ["documentary", "documental", "a factual film or programme about real people, events or subjects"],
  ["reality TV show", "reality show", "a television programme featuring real people in unscripted or partly structured situations"],
  ["soap opera", "telenovela / serie diaria", "a continuing television drama about the lives and relationships of a group of characters"],
  ["It makes me laugh.", "Me hace reír.", "a phrase used to say that something causes you to laugh"],
  ["It’s entertaining.", "Es entretenido.", "a phrase used to say that something is enjoyable and holds your attention"],
  ["The acting is brilliant.", "La interpretación es brillante.", "a phrase praising the quality of the actors' performances"],
  ["The storylines are gripping.", "Las tramas enganchan.", "a phrase saying that the continuing plots are extremely engaging"],
  ["The characters are great.", "Los personajes son geniales.", "a phrase expressing strong approval of the people represented in a story"],
  ["The plots are good.", "Las tramas son buenas.", "a phrase expressing approval of the stories or sequences of events"],
  ["It’s compelling.", "Es muy atractivo / te atrapa.", "a phrase saying that something holds your attention very strongly"],
  ["see", "ver sin hacer un esfuerzo deliberado", "to notice something with your eyes without deliberately trying to look"],
  ["look at", "mirar deliberadamente", "to direct your eyes towards something deliberately"],
  ["watch", "observar durante un tiempo, normalmente algo que cambia / se mueve", "to look at something for a period of time, especially something moving or changing"],
  ["read about", "leer sobre", "to get information about a subject by reading"],
  ["hear", "oír sin intentarlo", "to become aware of sound without deliberately trying"],
  ["listen to", "escuchar prestando atención", "to pay attention to a sound deliberately"],
  ["actor", "actor", "a person who performs a character in a film, play or television programme"],
  ["audience", "público", "the group of people watching or listening to a performance"],
  ["box office", "taquilla", "the place where tickets are sold, or the commercial success of a film or show"],
  ["cartoon", "película / serie de animación", "a film or programme made from animated drawings or images"],
  ["cast", "reparto", "all the actors performing in a film, play or programme"],
  ["costumes", "vestuario", "clothes worn by actors for a performance"],
  ["critic", "crítico", "a person who professionally judges and writes about films, books, theatre or art"],
  ["director", "director", "the person responsible for controlling the artistic production of a film or play"],
  ["interval", "descanso / entreacto", "a break between parts of a performance"],
  ["location", "localización de rodaje", "a real place where part of a film or programme is recorded"],
  ["musical", "musical", "a play or film in which songs and music are important parts of the story"],
  ["performance", "representación / actuación", "an occasion when actors, musicians or other performers present something to an audience"],
  ["plot", "trama", "the main sequence of events in a story"],
  ["rehearsal", "ensayo", "a practice session before a public performance"],
  ["reviews", "reseñas / críticas", "written or spoken evaluations of films, books, performances or other works"],
  ["scenery", "decorado", "the painted or constructed background used on a stage"],
  ["screen", "pantalla", "the surface on which films, television images or computer images are shown"],
  ["soundtrack", "banda sonora", "the recorded music and sounds used in a film or programme"],
  ["special effects", "efectos especiales", "visual or sound techniques used to create unusual or impossible scenes"],
  ["stage", "escenario", "the raised area where actors or performers appear"],
  ["subtitles", "subtítulos", "words shown on a screen that represent or translate spoken dialogue"],
  ["brilliant", "brillante", "extremely good or impressive"],
  ["confusing", "confuso", "difficult to understand clearly"],
  ["convincing", "convincente", "believable and able to make people accept something as true"],
  ["delightful", "encantador", "very pleasant and enjoyable"],
  ["dramatic", "dramático", "exciting, emotional or connected with drama"],
  ["dull", "soso / aburrido", "not interesting or exciting"],
  ["fascinating", "fascinante", "extremely interesting"],
  ["gripping", "absorbente / que engancha", "so exciting or interesting that it holds your attention completely"],
  ["imaginative", "imaginativo", "showing creativity and original ideas"],
  ["irritating", "irritante", "annoying or causing slight anger"],
  ["lively", "animado", "full of energy and activity"],
  ["memorable", "memorable", "worth remembering because it is special or striking"],
  ["moving", "conmovedor", "causing strong feelings, especially sadness or sympathy"],
  ["outstanding", "sobresaliente", "extremely good and clearly better than average"],
  ["predictable", "predecible", "easy to guess because it follows an expected pattern"],
  ["stunning", "impresionante", "extremely impressive or attractive"],
  ["superb", "excelente", "of extremely high quality"],
  ["tedious", "tedioso", "boring because it is too long, slow or repetitive"],
  ["uninspired", "poco inspirado", "not showing much creativity, originality or imagination"],

  ["atlas", "atlas", "a book containing maps"],
  ["biography", "biografía", "a written account of a person's life"],
  ["brochure", "folleto", "a small booklet giving information or advertising something"],
  ["catalogue", "catálogo", "a list or book showing items available for sale or display"],
  ["cookery book", "libro de cocina", "a book containing recipes and cooking instructions"],
  ["detective story", "historia policíaca", "a story about solving a crime or mystery"],
  ["fantasy", "fantasía", "fiction involving magic, imaginary worlds or impossible events"],
  ["ghost story", "historia de fantasmas", "a story about ghosts or supernatural events"],
  ["guidebook", "guía", "a book giving practical information about a place for visitors"],
  ["romance", "novela romántica", "a story whose main focus is a romantic relationship"],
  ["science fiction novel", "novela de ciencia ficción", "a novel based on imagined scientific or technological developments"],
  ["textbook", "libro de texto", "a book used for studying a particular subject"],
  ["thriller", "thriller", "an exciting story involving danger, crime or suspense"],
  ["groan", "gemir", "to make a low sound because of pain, annoyance or effort"],
  ["shriek", "chillar / dar un alarido", "to make a very high, loud cry"],
  ["yell", "gritar", "to shout very loudly"],
  ["whimper", "gemir débilmente", "to make quiet weak sounds because of fear, pain or sadness"],
  ["creep", "avanzar sigilosamente", "to move slowly and quietly so as not to be noticed"],
  ["dart", "moverse rápidamente", "to move suddenly and quickly in a particular direction"],
  ["dash", "salir corriendo", "to move or run somewhere very quickly"],
  ["stumble", "tropezar", "to lose your balance while walking or running, often after hitting something"],
  ["notice", "notar", "to become aware of something by seeing, hearing or feeling it"],
  ["glimpse", "vislumbrar / vistazo", "to see something for a very short time"],
  ["nod", "asentir con la cabeza", "to move your head up and down, often to show agreement"],
  ["gaze", "mirar fijamente", "to look steadily at something for a long time, often with interest"],
  ["peer", "mirar con dificultad / atentamente", "to look carefully, especially because something is difficult to see"],
  ["spot", "divisar", "to notice or see something, especially after looking for it"],
  ["blink", "parpadear", "to close and open your eyes quickly"],
  ["view", "vista / contemplar", "what can be seen from a place, or to look at something"],
  ["tremble", "temblar", "to shake slightly because of fear, cold or strong emotion"],
  ["witness", "presenciar / testigo", "to see an event happen, especially something important or serious"],
  ["stare", "mirar fijamente", "to look at someone or something for a long time with your eyes wide open"],
  ["observe", "observar", "to watch or notice something carefully"],
  ["sigh", "suspirar", "to breathe out slowly and audibly because of emotion or tiredness"],
  ["glance", "echar un vistazo", "to look quickly at something"],
  ["breathe", "respirar", "to take air into and send it out of your lungs"],
  ["novelist ↔ journalist", "novelista ↔ periodista", "a person who writes novels ↔ a person who reports or writes news"],
  ["called", "titulado / llamado", "having a particular name or title"],
  ["remember ↔ remind", "recordar ↔ recordar a alguien", "to keep or bring something back to your own mind ↔ to make another person remember something"],
  ["fiction ↔ non-fiction", "ficción ↔ no ficción", "writing about invented people or events ↔ factual writing about real subjects"],
  ["character ↔ personality", "personaje ↔ personalidad", "a person represented in a story ↔ the set of qualities that make someone behave in a particular way"],
  ["relationship ↔ relative", "relación ↔ pariente", "a connection between people ↔ a member of your family"],
  ["borrow ↔ lend", "tomar prestado ↔ prestar", "to receive something temporarily and return it later ↔ to give something temporarily and expect it back"],
  ["library ↔ bookshop", "biblioteca ↔ librería", "a place where books can be borrowed ↔ a shop where books are sold"],
  ["request ↔ ask", "solicitar ↔ preguntar / pedir", "to formally ask for something ↔ to say a question or request something"],
  ["entertaining ↔ entertained", "entretenido (cosa) ↔ entretenido (persona)", "interesting or enjoyable enough to hold attention ↔ feeling interested and amused"],
  ["chapter ↔ verse", "capítulo ↔ verso", "a main section of a book ↔ a line or group of lines in poetry or a song"],
  ["be mad about crime novels", "ser fanático de las novelas policíacas", "to be extremely enthusiastic about crime novels"],
  ["make me think", "hacerme pensar", "to cause me to consider ideas carefully"],
  ["move really fast", "avanzar muy rápido (una historia)", "to develop very quickly, especially when describing the pace of a story"],
  ["a tough guy", "un tipo duro", "a man presented as physically or emotionally strong and difficult to intimidate"],
  ["a book you can’t put down", "un libro que no puedes dejar", "a book so interesting that you want to keep reading it"],
  ["burglary → burglar → burgle", "robo en vivienda → ladrón → entrar a robar", "the crime of entering a building to steal → a person who commits that crime → to enter a building illegally to steal"],
  ["robbery → robber → rob", "robo / atraco → atracador → robar a alguien / un lugar", "the crime of taking property by force or threat → a person who robs → to steal from a person or place"],
  ["theft → thief → steal", "hurto / robo → ladrón → robar una cosa", "the crime of taking something illegally → a person who steals → to take something that is not yours"],
  ["shoplifting → shoplifter → shoplift", "hurto en tiendas → ladrón de tienda → hurtar en tiendas", "the crime of stealing from a shop → a person who does this → to steal goods from a shop"],
  ["murder → murderer → murder", "asesinato → asesino → asesinar", "the intentional killing of a person → a person who commits murder → to kill someone intentionally"],
  ["steal something", "robar una cosa", "to take a thing that belongs to someone else without permission"],
  ["rob someone / a place", "robar a una persona / atracar un lugar", "to steal money or property from a person / to steal from a particular place"],
  ["be stolen", "ser robado; steal aparece con frecuencia en pasiva", "to be taken illegally by someone else"],
];
