import type { VocabularyGloss } from "./glosses";

export const peopleGlosses: VocabularyGloss[] = [
  ["salt", "sal", "a white mineral used to add flavour to food and needed in small amounts by the body"],
  ["fat", "grasa", "a nutrient that provides energy and is found in foods such as oils, butter and meat"],
  ["vitamins", "vitaminas", "natural substances needed in small amounts for normal growth and health"],
  ["protein", "proteína", "a nutrient needed for growth and repair of body tissues"],
  ["fibre", "fibra", "the part of plant food that helps the digestive system work properly"],
  ["carbohydrate", "carbohidrato", "a nutrient such as sugar or starch that provides the body with energy"],
  ["sugar", "azúcar", "a sweet substance used in food and also a type of carbohydrate"],
  ["calories", "calorías", "units used to measure the energy provided by food"],
  ["lean meat", "carne magra", "meat containing relatively little fat"],
  ["energy", "energía", "the physical power needed to be active or do work"],
  ["substantial portions", "raciones abundantes", "fairly large amounts of food served to one person"],
  ["dairy products", "productos lácteos", "foods made from milk, such as cheese and yoghurt"],
  ["junk food", "comida basura", "food that is convenient but often high in fat, sugar or salt and low in nutritional value"],
  ["regular training", "entrenamiento regular", "exercise or practice done consistently over time"],
  ["handle stress", "gestionar el estrés", "to deal successfully with pressure or worry"],
  ["get enough sleep", "dormir lo suficiente", "to sleep for the amount of time your body needs"],
  ["be high in ...", "tener un alto contenido de...", "to contain a large amount of a particular nutrient or substance"],
  ["be low in ...", "tener un bajo contenido de...", "to contain only a small amount of a particular nutrient or substance"],
  ["eat a healthy diet", "llevar una dieta saludable", "to regularly eat food that supports good health"],
  ["staple diet", "dieta básica / alimento base", "the main food or foods regularly eaten by a person or community"],
  ["go on a diet", "ponerse a dieta", "to begin following a particular eating plan, often to lose weight or improve health"],
  ["a low-salt diet", "una dieta baja en sal", "an eating plan containing only a small amount of salt"],
  ["put on weight", "ganar peso", "to become heavier"],
  ["cut out fat", "eliminar la grasa de la dieta", "to stop eating fat or foods containing a lot of fat"],
  ["cut down on chocolate", "reducir el consumo de chocolate", "to eat less chocolate than before"],
  ["give up smoking", "dejar de fumar", "to stop smoking permanently"],
  ["go to the gym regularly", "ir al gimnasio con regularidad", "to exercise at a gym on a consistent basis"],
  ["keep to", "seguir / respetar (una dieta, plan)", "to follow a plan, rule or agreement and not change from it"],
  ["cut down on", "reducir el consumo de", "to reduce the amount of something you use or consume"],
  ["put on", "ganar (peso)", "to gain weight in this health-related use"],
  ["live on", "alimentarse básicamente de", "to eat mainly a particular type of food"],
  ["get round to", "encontrar por fin el momento para hacer algo", "to finally find the time or motivation to do something"],
  ["take up", "empezar una actividad", "to begin doing an activity regularly"],
  ["go for", "salir a / ir a hacer (a walk, a run)", "to go somewhere in order to do an activity such as walking or running"],
  ["come down with", "ponerse enfermo de", "to become ill with a particular illness"],
  ["get a blister", "hacerse una ampolla", "to develop a small painful bubble of skin caused by rubbing or burning"],
  ["have a stomach upset", "tener malestar estomacal", "to have a temporary problem with digestion causing pain, nausea or diarrhoea"],
  ["have a sore throat", "tener dolor de garganta", "to have pain or irritation in the throat"],
  ["feel run down", "sentirse agotado / decaído", "to feel tired, weak and generally unwell"],
  ["lose your voice", "quedarse sin voz", "to become temporarily unable to speak normally"],
  ["be jet-lagged", "tener desfase horario", "to feel tired or confused after travelling across several time zones"],
  ["flu", "gripe", "an infectious illness causing fever, tiredness and body aches"],
  ["cough", "tos", "a sudden forceful movement of air from the lungs, often caused by illness"],
  ["cold", "resfriado", "a common mild illness affecting the nose and throat"],
  ["hay fever", "alergia al polen / fiebre del heno", "an allergy to pollen that causes sneezing and irritation of the eyes and nose"],
  ["casualty department", "urgencias", "the hospital department that treats people who need immediate medical attention"],
  ["local surgery", "consulta médica local", "a local doctor's office or clinic in British English"],
  ["stitches", "puntos de sutura", "threads used by medical staff to close a cut or wound"],
  ["local anaesthetic", "anestesia local", "a drug that makes one part of the body temporarily unable to feel pain"],
  ["antihistamines", "antihistamínicos", "medicines used to reduce the symptoms of allergies"],
  ["antibiotics", "antibióticos", "medicines used to treat infections caused by bacteria"],
  ["prescription", "receta médica", "a doctor's written instruction allowing a patient to obtain medicine"],
  ["pharmacy", "farmacia", "a shop or department where medicines are prepared and sold"],
  ["plaster", "escayola", "a hard protective covering used to support a broken bone"],
  ["bandage", "vendaje", "a strip of material used to cover or support an injured part of the body"],
  ["vaccination", "vacunación", "the act of giving a vaccine to protect someone against disease"],
  ["disease", "enfermedad", "an illness affecting the body or mind, especially one with a particular cause"],
  ["yellow fever", "fiebre amarilla", "a serious tropical viral disease spread by mosquitoes"],
  ["scales", "báscula", "a device used for measuring body weight"],
  ["symptoms", "síntomas", "physical or mental signs that show someone may have an illness"],
  ["treatment", "tratamiento", "medical care given to improve an illness or injury"],
  ["make up", "inventar (una historia / excusa)", "to invent a story, explanation or excuse that is not true"],
  ["make up for", "compensar", "to compensate for something bad or missing"],
  ["make for", "dirigirse hacia", "to move or travel towards a place"],
  ["make out", "entender / distinguir con dificultad", "to manage to see, hear or understand something with difficulty"],
  ["make into", "transformar en", "to change someone or something into a different form or state"],
  ["receipt", "recibo / comprobante de pago", "a document showing that money has been paid for something"],
  ["recipe", "receta de cocina", "a set of instructions for preparing a particular dish"],

  ["ashamed", "avergonzado por algo que has hecho", "feeling guilty or embarrassed because of something you have done"],
  ["confident", "seguro de sí mismo", "feeling sure about your abilities or about what will happen"],
  ["disappointed", "decepcionado", "unhappy because something was not as good as you hoped"],
  ["embarrassed", "avergonzado / incómodo socialmente", "feeling uncomfortable or self-conscious in a social situation"],
  ["excited", "emocionado", "feeling very happy, interested or enthusiastic about something"],
  ["guilty", "culpable", "feeling that you have done something wrong"],
  ["jealous", "celoso / envidioso", "upset because someone has something you want or because you fear losing someone's attention"],
  ["proud", "orgulloso", "feeling pleased about an achievement or about someone connected with you"],
  ["relaxed", "relajado", "calm and free from tension or worry"],
  ["upset", "disgustado / afectado", "unhappy, worried or emotionally disturbed"],
  ["happy", "feliz", "feeling or showing pleasure and satisfaction"],
  ["keen", "entusiasmado / muy interesado", "very interested or enthusiastic about doing something"],
  ["thrilled", "encantadísimo / emocionadísimo", "extremely pleased and excited"],
  ["eager", "deseoso", "very interested in doing or having something soon"],
  ["enthusiastic", "entusiasta", "showing strong interest and excitement"],
  ["nervous", "nervioso", "worried or slightly afraid about what might happen"],
  ["apprehensive", "inquieto / con temor ante lo que puede pasar", "worried or anxious because you think something unpleasant may happen"],
  ["amazed / surprised / astonished", "sorprendido / asombrado / muy asombrado", "very surprised / feeling surprise / extremely surprised"],
  ["annoyed / angry / furious", "molesto / enfadado / furioso", "slightly angry or irritated / feeling strong displeasure / extremely angry"],
  ["depressed / fed up / miserable", "deprimido / harto / miserable", "very unhappy and without hope / bored or annoyed with a situation / extremely unhappy"],
  ["frightened / scared / afraid / terrified", "asustado / asustado / con miedo / aterrorizado", "feeling fear / feeling fear / feeling worried or frightened / feeling extreme fear"],
  ["pleased / glad / delighted", "contento / contento / encantado", "happy and satisfied / happy about something / extremely pleased"],
  ["worried / anxious / concerned", "preocupado / ansioso / preocupado", "thinking about possible problems / worried and tense / worried about a particular situation"],
  ["worried about", "preocupado por", "feeling anxious about a particular person, thing or situation"],
  ["surprised that", "sorprendido de que", "feeling surprise because a particular fact is true"],
  ["afraid of", "tener miedo de", "feeling fear about a person, thing or situation"],
  ["upset that", "afectado porque", "feeling unhappy because a particular fact or event has occurred"],
  ["pleased to + infinitive", "encantado de hacer algo", "happy to do a particular action"],
  ["annoyed with someone", "molesto con alguien", "slightly angry with a particular person"],
  ["sorry (that) ...", "sentir / lamentar que...", "a pattern used to express regret, sympathy or apology about a situation"],
  ["pleased (that) ...", "estar contento de que...", "a pattern used to express happiness about a fact or situation"],
  ["bored ↔ boring", "aburrido (persona) ↔ aburrido (cosa/situación)", "feeling uninterested because something is dull ↔ causing people to feel uninterested"],
  ["disappointed ↔ disappointing", "decepcionado ↔ decepcionante", "feeling unhappy because expectations were not met ↔ causing disappointment"],
  ["surprised ↔ surprising", "sorprendido ↔ sorprendente", "feeling surprise ↔ causing surprise"],
  ["excited ↔ exciting", "emocionado ↔ emocionante", "feeling enthusiasm or eagerness ↔ causing enthusiasm or excitement"],
  ["worried ↔ worrying", "preocupado ↔ preocupante", "feeling anxious ↔ causing concern or anxiety"],
  ["terrified ↔ terrifying", "aterrorizado ↔ aterrador", "feeling extreme fear ↔ causing extreme fear"],
  ["relaxed ↔ relaxing", "relajado ↔ relajante", "feeling calm ↔ helping someone feel calm"],
  ["fear → frighten → frightened / frightening", "miedo → asustar → asustado / aterrador", "the emotion caused by danger → to make someone afraid → feeling fear / causing fear"],
  ["amazement → amaze → amazed / amazing", "asombro → asombrar → asombrado / asombroso", "a feeling of great surprise → to surprise someone greatly → feeling great surprise / causing great surprise"],
  ["annoyance → annoy → annoyed / annoying", "molestia → molestar → molesto / molesto-irritante", "the feeling of being slightly angry → to irritate someone → feeling irritated / causing irritation"],
  ["embarrassment → embarrass → embarrassed / embarrassing", "vergüenza → avergonzar → avergonzado / vergonzoso", "the feeling of social discomfort → to make someone feel self-conscious → feeling embarrassed / causing embarrassment"],
  ["pleasure → please → pleased / pleasing", "placer → agradar → contento / agradable", "a feeling of enjoyment → to make someone happy or satisfied → feeling satisfied / giving pleasure"],
  ["excitement → excite → excited / exciting", "emoción → emocionar → emocionado / emocionante", "a feeling of enthusiasm and eagerness → to make someone feel excited → feeling excited / causing excitement"],
  ["depression → depressed / depressing", "depresión → deprimido / deprimente", "a state of deep unhappiness → very unhappy / causing sadness or hopelessness"],
  ["anger → angry", "ira → enfadado", "a strong feeling of displeasure → feeling strong displeasure"],
  ["pride → proud", "orgullo → orgulloso", "pleasure in an achievement or quality → feeling that pleasure"],
  ["anxiety → anxious", "ansiedad → ansioso", "a feeling of worry or nervousness → worried or nervous"],
  ["misery → miserable", "miseria / desdicha → miserable", "great unhappiness or suffering → extremely unhappy"],
  ["jealousy → jealous", "celos / envidia → celoso / envidioso", "the feeling of jealousy → feeling jealous"],

  ["energetic", "enérgico", "having or showing a lot of energy"],
  ["determined", "decidido", "strongly wanting to achieve something and not easily giving up"],
  ["ambitious", "ambicioso", "strongly wanting to be successful or achieve important goals"],
  ["outstanding", "sobresaliente", "extremely good and clearly better than average"],
  ["fashionable", "con estilo / de moda", "popular or considered stylish at a particular time"],
  ["fit", "en forma", "healthy and physically strong"],
  ["self-confident", "seguro de sí mismo", "believing in your own abilities and judgement"],
  ["charming", "encantador", "pleasant and attractive in a way that makes people like you"],
  ["sympathetic", "comprensivo", "showing that you understand and care about another person's problems"],
  ["dedicated", "dedicado", "giving a lot of time and effort to something because it is important to you"],
  ["versatile", "versátil", "able to do many different things well"],
  ["talented", "con talento", "having a natural ability to do something well"],
  ["graceful", "elegante / con gracia", "moving or behaving in an attractive, smooth and controlled way"],
  ["courageous", "valiente", "showing bravery in a difficult or dangerous situation"],
  ["devoted", "entregado / muy dedicado", "giving a lot of love, attention or effort to someone or something"],
  ["easy-going", "de trato fácil / relajado", "relaxed, tolerant and not easily worried or annoyed"],
  ["thoughtful", "considerado / atento", "kind and careful about other people's feelings and needs"],
  ["imaginative", "imaginativo", "good at producing original and creative ideas"],
  ["shy", "tímido", "nervous or uncomfortable when meeting or speaking to people"],
  ["selfish", "egoísta", "caring mainly about your own needs rather than other people's"],
  ["hopeless", "sin esperanza / muy malo en algo", "having no chance of success, or being extremely bad at doing something"],
  ["stubborn", "terco", "unwilling to change your opinion or behaviour even when others try to persuade you"],
  ["outgoing", "sociable", "friendly, confident and comfortable meeting people"],
  ["bossy", "mandón", "always telling other people what to do in an annoying way"],
  ["sensitive", "sensible emocionalmente / fácil de herir", "easily affected emotionally or easily upset by what others say or do"],
  ["sensible", "sensato", "showing good judgement and practical understanding"],
  ["caring", "cariñoso / atento", "kind and concerned about other people's needs"],
  ["cheerful", "alegre", "noticeably happy and positive"],
  ["demanding", "exigente", "requiring a lot of effort, attention or skill"],
  ["talkative", "hablador", "liking to talk a lot"],
  ["generous", "generoso", "willing to give time, money or help freely"],
  ["considerate", "considerado", "careful not to inconvenience or upset other people"],
  ["competitive", "competitivo", "wanting very much to win or be more successful than others"],
  ["lively", "animado", "full of energy and enthusiasm"],
  ["impatient", "impaciente", "easily annoyed by waiting or delays"],
  ["unreliable", "poco fiable", "not able to be trusted to do what is expected"],
  ["unkind", "poco amable", "not kind or considerate"],
  ["amusing ↔ serious", "divertido ↔ serio", "funny or entertaining ↔ thoughtful, important or not humorous"],
  ["adventurous ↔ cautious", "aventurero ↔ prudente", "willing to take risks and try new things ↔ careful to avoid danger or mistakes"],
  ["generous ↔ mean", "generoso ↔ tacaño / mezquino", "willing to give freely ↔ unwilling to give or share"],
  ["gentle ↔ aggressive", "amable / suave ↔ agresivo", "calm, kind or soft ↔ behaving in a forceful or hostile way"],
  ["hard-working ↔ lazy", "trabajador ↔ vago", "putting a lot of effort into work ↔ unwilling to work or make effort"],
  ["modest ↔ arrogant", "modesto ↔ arrogante", "not talking proudly about yourself ↔ believing you are better or more important than others"],
  ["polite ↔ rude", "educado ↔ maleducado", "showing good manners ↔ behaving in an impolite or offensive way"],
  ["relaxed ↔ tense", "relajado ↔ tenso", "calm and free from worry ↔ nervous and unable to relax"],
  ["self-confident ↔ shy", "seguro de sí mismo ↔ tímido", "sure of your own abilities ↔ nervous and uncomfortable with other people"],
  ["sensitive", "se altera o hiere con facilidad", "easily emotionally affected or upset"],
  ["sensible", "muestra buen juicio / sensato", "showing practical good judgement"],
  ["sympathetic", "comprende los problemas de otras personas; no significa «simpático»", "showing understanding and concern for someone else's difficulties"],
  ["polite → impolite", "educado → maleducado", "showing good manners → not showing good manners"],
  ["patient → impatient", "paciente → impaciente", "able to wait calmly → unable to wait calmly"],
  ["possible → impossible", "posible → imposible", "able to happen or be done → unable to happen or be done"],
  ["popular → unpopular", "popular → impopular", "liked by many people → not liked by many people"],
  ["kind → unkind", "amable → poco amable", "friendly and caring → not friendly or caring"],
  ["imaginative → unimaginative", "imaginativo → poco imaginativo", "creative and full of ideas → lacking creativity or new ideas"],
  ["considerate → inconsiderate", "considerado → desconsiderado", "careful about other people's feelings → not caring enough about other people's feelings"],
  ["convenient → inconvenient", "conveniente → inconveniente", "easy and suitable for your situation → causing difficulty or trouble"],
  ["expensive → inexpensive", "caro → barato / no caro", "costing a lot of money → not costing much money"],
  ["honest → dishonest", "honesto → deshonesto", "truthful and trustworthy → not truthful or trustworthy"],
  ["satisfied → dissatisfied", "satisfecho → insatisfecho", "pleased because expectations are met → not pleased because expectations are not met"],
  ["relevant → irrelevant", "relevante → irrelevante", "directly connected with the subject → not connected with the subject"],
  ["responsible → irresponsible", "responsable → irresponsable", "reliable and accountable → not showing enough care or responsibility"],
  ["regular → irregular", "regular → irregular", "following a normal or repeated pattern → not following a regular pattern"],
  ["unhappiness / disapproval / impatience", "infelicidad / desaprobación / impaciencia", "the state of being unhappy / a negative opinion about something / inability to wait calmly"],
  ["unlock / dislike", "desbloquear / no gustar", "to open something that was locked / to not like someone or something"],
  ["thank → thankful", "agradecer / gratitud → agradecido", "to express gratitude → feeling or showing gratitude"],
  ["care → careless", "cuidado → descuidado", "attention given to avoid harm or mistakes → not giving enough attention"],
  ["power → powerful", "poder → poderoso", "the ability to control or influence → having a lot of power"],
  ["pain → painful", "dolor → doloroso", "physical or emotional suffering → causing pain"],
  ["harm → harmless", "daño → inofensivo", "damage or injury → unable or unlikely to cause harm"],
  ["grace → graceful", "gracia → elegante", "smooth beauty in movement or style → moving in a smooth and attractive way"],
  ["colour → colourless", "color → incoloro", "the visual quality produced by light → having no colour"],

  ["fall out with someone", "pelearse / dejar de hablarse con alguien", "to have an argument and stop being friendly with someone"],
  ["speak to each other", "hablar el uno con el otro", "to communicate by talking with one another"],
  ["get in touch", "ponerse en contacto", "to contact someone"],
  ["make up", "hacer las paces", "to become friendly again after an argument"],
  ["tell each other everything", "contárselo todo", "to share all personal information with one another"],
  ["fall madly in love", "enamorarse locamente", "to begin to love someone very strongly"],
  ["get on well together", "llevarse bien", "to have a friendly and comfortable relationship"],
  ["get to know someone", "llegar a conocer a alguien", "to gradually learn more about a person"],
  ["lose touch", "perder el contacto", "to stop communicating with someone over time"],
  ["enjoy each other’s company", "disfrutar de la compañía mutua", "to like spending time together"],
  ["keep in touch", "mantener el contacto", "to continue communicating with someone"],
  ["make friends", "hacer amigos", "to begin friendly relationships with people"],
  ["have things in common", "tener cosas en común", "to share interests, experiences or characteristics"],
  ["close friend", "amigo cercano", "a friend with whom you have a strong and trusting relationship"],
  ["best friend", "mejor amigo", "the friend you feel closest to"],
  ["old friend", "amigo de hace tiempo", "a person who has been your friend for a long time"],
  ["good friend", "buen amigo", "a friend with whom you have a positive and supportive relationship"],
  ["get engaged to", "prometerse con", "to agree formally to marry someone"],
  ["get married to", "casarse con", "to become someone's husband, wife or spouse through marriage"],
  ["get divorced from", "divorciarse de", "to legally end a marriage with someone"],
  ["go out with", "salir con", "to have a romantic relationship with someone"],
  ["propose to", "pedir matrimonio a", "to ask someone to marry you"],
  ["classmate", "compañero de clase", "a person who is in the same class as you"],
  ["colleague", "compañero de trabajo", "a person you work with"],
  ["cousin", "primo", "a child of your aunt or uncle"],
  ["partner", "pareja", "the person with whom you have a romantic or long-term relationship"],
  ["nephew", "sobrino", "a son of your brother or sister"],
  ["widow", "viuda", "a woman whose spouse has died and who has not remarried"],
  ["flatmate", "compañero de piso", "a person who shares a flat with you"],
  ["couple", "pareja", "two people who are married or in a romantic relationship"],
  ["acquaintance", "conocido", "a person you know but who is not a close friend"],
  ["neighbour", "vecino", "a person who lives near you"],
  ["aunt", "tía", "the sister of one of your parents, or the wife of your uncle"],
  ["stepfather", "padrastro", "the man married to your parent who is not your biological father"],
  ["sister-in-law", "cuñada", "the sister of your spouse or the wife of your sibling"],
  ["boyfriend", "novio", "a male romantic partner"],
  ["grandparents", "abuelos", "the parents of your mother or father"],
  ["fiancé / fiancée", "prometido / prometida", "a man engaged to be married / a woman engaged to be married"],
  ["penfriend", "amigo por correspondencia", "a person you become friends with by exchanging letters or messages"],
  ["lifetime", "vida / duración de la vida", "the entire period during which a person is alive"],
  ["destiny", "destino", "the events believed to be fixed or likely to happen in someone's future"],
  ["eldest", "el mayor de varios hermanos", "the oldest member of a group of brothers or sisters"],
  ["support a family", "mantener económicamente a una familia", "to provide the money needed for a family's living costs"],
  ["roots", "raíces / origen", "a person's family, cultural or geographical origins"],
  ["loyalty", "lealtad", "the quality of being faithful and supportive"],
  ["community", "comunidad", "a group of people living in the same area or sharing something in common"],
  ["be brought up", "criarse", "to be raised and cared for during childhood"],
  ["background", "origen / contexto familiar", "the family, social or cultural circumstances from which someone comes"],
  ["make a fortune", "hacer una fortuna", "to earn or obtain a very large amount of money"],
  ["inherit", "heredar", "to receive money, property or characteristics from someone who has died or from family"],
  ["donate", "donar", "to give money, goods or blood to help a person or organisation"],
  ["lifetime ↔ generation", "vida de una persona ↔ generación", "the whole period of one person's life ↔ people born and living at roughly the same time"],
  ["outlook ↔ destiny", "perspectiva / actitud ↔ destino", "a person's general attitude to life ↔ the future events believed to be fixed for someone"],
  ["eldest ↔ older", "el mayor de 3+ ↔ mayor que otro", "the oldest among three or more siblings ↔ comparative form meaning more advanced in age"],
  ["support ↔ provide", "mantener / apoyar ↔ proporcionar", "to give help or financial assistance ↔ to supply something that is needed"],
  ["roots ↔ ancestors", "raíces / origen ↔ antepasados", "family or cultural origins ↔ family members who lived many generations ago"],
  ["household ↔ community", "hogar / personas de una casa ↔ comunidad", "all the people living together in one home ↔ a wider group of people connected by place or shared interests"],
  ["brought up ↔ grown up", "criado / educado ↔ adulto / haber crecido", "raised during childhood ↔ fully adult or having developed from childhood"],
  ["fortune ↔ funds", "fortuna ↔ fondos", "a very large amount of money ↔ money available for a particular purpose"],
  ["inherit ↔ be granted", "heredar ↔ recibir/concederse", "to receive property or money from someone after death ↔ to be officially given something"],
  ["save ↔ donate", "ahorrar / salvar ↔ donar", "to keep money for future use or rescue someone ↔ to give something voluntarily to help others"],
  ["be full of life", "estar lleno de energía", "to be very energetic and lively"],
  ["Life’s too short.", "La vida es demasiado corta.", "an expression used to say that time should not be wasted on unimportant or unpleasant things"],
  ["Get a life!", "¡Búscate una vida! / deja de obsesionarte", "an informal expression telling someone to stop focusing on something trivial and do more worthwhile things"],
  ["How’s life?", "¿Qué tal la vida?", "an informal way of asking how someone is and how things are going"],
  ["It’s her life.", "Es su vida.", "an expression meaning that a person has the right to make her own choices"],
  ["That’s life.", "Así es la vida.", "an expression accepting that unpleasant or disappointing things sometimes happen"],
];
