import type { VocabularyGloss } from "./glosses";

export const placesGlosses: VocabularyGloss[] = [
  ["passport", "pasaporte", "an official document proving your identity and nationality for international travel"],
  ["visa", "visado", "official permission allowing someone to enter, stay in or leave a country"],
  ["terminal", "terminal", "a building at an airport where passengers arrive or depart"],
  ["check-in desk", "mostrador de facturación", "the airport counter where passengers register for a flight and leave luggage"],
  ["boarding pass", "tarjeta de embarque", "a document that allows a passenger to board a plane"],
  ["passport control", "control de pasaportes", "the place where officials check travellers' passports"],
  ["security check", "control de seguridad", "the airport procedure where passengers and luggage are checked for safety"],
  ["departure lounge", "sala de embarque", "the airport waiting area used before boarding a flight"],
  ["departure board", "panel de salidas", "a display showing information about departing flights or trains"],
  ["gate", "puerta de embarque", "the airport area where passengers board a particular flight"],
  ["cabin crew", "tripulación de cabina", "the staff who look after passengers on an aircraft"],
  ["fasten your seat belt", "abrocharse el cinturón", "to secure the safety belt around your body"],
  ["take-off", "despegue", "the moment when an aircraft leaves the ground"],
  ["landing", "aterrizaje", "the act of an aircraft coming down to the ground"],
  ["runway", "pista de aterrizaje", "the long strip of ground used by aircraft for taking off and landing"],
  ["wing", "ala", "one of the large flat parts extending from the side of an aircraft"],
  ["headset", "auriculares", "a set of headphones, often with a microphone"],
  ["board", "embarcar", "to get onto a plane, train, ship or bus"],
  ["carriage", "vagón", "one of the sections of a passenger train"],
  ["commute", "desplazarse regularmente al trabajo/estudio", "to travel regularly between home and work or study"],
  ["double-decker", "autobús de dos pisos", "a bus with two levels for passengers"],
  ["single-decker", "autobús de un piso", "a bus with one passenger level"],
  ["escalator", "escalera mecánica", "a moving staircase carrying people between floors"],
  ["fare", "tarifa / billete", "the amount of money paid for a journey on public transport or in a taxi"],
  ["meter", "taxímetro", "a device in a taxi that calculates the fare"],
  ["pass", "abono / pase", "a ticket or document allowing repeated or special access"],
  ["platform", "andén", "the raised area beside a railway track where passengers get on or off trains"],
  ["taxi rank", "parada de taxis", "a place where taxis wait for passengers"],
  ["rush hour", "hora punta", "the busiest time of day for traffic and public transport"],
  ["season ticket", "abono de temporada / transporte", "a ticket allowing repeated travel or entry for a fixed period"],
  ["sliding doors", "puertas correderas", "doors that open by moving sideways"],
  ["stop", "parada", "a place where a bus, tram or other vehicle stops for passengers"],
  ["tip", "propina", "extra money given to someone for a service"],
  ["seat", "asiento", "a place designed for one person to sit"],
  ["accommodation [U]", "alojamiento", "places where people stay temporarily; an uncountable noun in this use"],
  ["equipment [U]", "equipamiento", "the tools or objects needed for an activity; an uncountable noun"],
  ["luggage [U]", "equipaje", "bags and suitcases used when travelling; an uncountable noun"],
  ["cash [U]", "efectivo", "money in notes and coins; an uncountable noun"],
  ["parking [U]", "aparcamiento como actividad/espacio", "the act or provision of leaving vehicles in a place; usually uncountable"],
  ["transport [U]", "transporte", "systems or methods for moving people or goods; usually uncountable"],
  ["hotel [C]", "hotel", "a building providing paid accommodation; a countable noun"],
  ["vehicle [C]", "vehículo", "a machine used for transporting people or goods; a countable noun"],
  ["suitcase [C]", "maleta", "a rectangular travel case for clothes and belongings; a countable noun"],
  ["tent [C]", "tienda de campaña", "a portable fabric shelter used for camping; a countable noun"],
  ["car park [C]", "aparcamiento", "an area where cars can be left; a countable noun"],
  ["coin [C]", "moneda", "a small round piece of metal used as money; a countable noun"],
  ["travel [U]", "actividad general de viajar", "the general activity of travelling; normally uncountable"],
  ["journey [C]", "trayecto de un lugar a otro", "an occasion of travelling from one place to another"],
  ["trip [C]", "viaje normalmente corto, con estancia y regreso", "a journey or visit, usually for a limited time and often involving a return"],
  ["go on a trip / journey", "irse de viaje / hacer un trayecto", "to take part in a trip / to travel from one place to another"],
  ["make a journey", "hacer un trayecto", "to travel from one place to another"],
  ["take a trip", "hacer un viaje", "to go somewhere and usually return after a limited period"],
  ["by road / train / boat", "por carretera / tren / barco", "using roads as the route / travelling by train / travelling by boat"],
  ["a quiet spot", "un lugar tranquilo", "a peaceful small place or location"],
  ["resort", "complejo / destino turístico", "a place where many people go for holidays"],
  ["somewhere abroad", "algún lugar en el extranjero", "a place in a foreign country"],
  ["activity holiday", "vacaciones de actividades", "a holiday focused on sports or organised activities"],
  ["seaside holiday", "vacaciones en la costa", "a holiday spent by the sea"],
  ["sightseeing holiday", "vacaciones de turismo", "a holiday mainly spent visiting famous places and attractions"],
  ["visit museums and sites", "visitar museos y lugares de interés", "to go to museums and important historical or tourist places"],
  ["get fit", "ponerse en forma", "to become physically healthier and stronger"],
  ["guesthouse", "pensión / alojamiento pequeño", "a small place providing accommodation, often more personal than a hotel"],
  ["campsite", "camping", "a place where people can stay in tents or caravans"],
  ["get to know new places", "conocer lugares nuevos", "to become familiar with places you have not visited before"],
  ["get away from routine", "desconectar de la rutina", "to escape temporarily from normal everyday habits"],
  ["get together with family", "reunirse con la familia", "to meet and spend time with family members"],
  ["port", "ciudad / puerto", "a town or city with a harbour where ships arrive and leave"],
  ["market town", "localidad con mercado tradicional", "a town that traditionally developed around a regular market"],
  ["new town / city", "ciudad de nueva creación", "a recently planned and developed town / a recently planned and developed city"],
  ["seaside town", "localidad costera", "a town on the coast, often popular with visitors"],
  ["capital city", "capital", "the city where a country's government is based"],
  ["industrial town / city", "ciudad industrial", "a town strongly connected with industry / a city strongly connected with industry"],
  ["rural area", "zona rural", "an area of countryside rather than a town or city"],
  ["historic town / city", "ciudad histórica", "a town with important history / a city with important history"],
  ["wide open spaces", "grandes espacios abiertos", "large areas with few buildings or obstacles"],
  ["leisure facilities", "instalaciones de ocio", "places and services provided for recreation and free-time activities"],
  ["an ideal location for a family day out", "un lugar ideal para pasar el día en familia", "a very suitable place for a family to visit for the day"],
  ["narrow stone streets", "calles estrechas de piedra", "small streets made or lined with stone"],
  ["picturesque centre", "centro pintoresco", "an attractive town centre with a traditional or visually pleasing appearance"],
  ["in the heart of a region", "en el corazón de una región", "in the central or most important part of a region"],
  ["fast-growing region", "región de rápido crecimiento", "an area whose population or economy is increasing quickly"],
  ["old market square", "antigua plaza del mercado", "a historic open area where markets were or are held"],
  ["completely unspoiled", "completamente intacto / no deteriorado", "not damaged or changed by development or tourism"],
  ["up-to-date shopping centres", "centros comerciales modernos", "modern shopping centres with current facilities and design"],
  ["lively nightlife", "vida nocturna animada", "active and exciting evening and night entertainment"],
  ["ancient churches", "iglesias antiguas", "very old church buildings"],
  ["impressive medieval buildings", "edificios medievales impresionantes", "striking buildings dating from the medieval period"],
  ["cosmopolitan atmosphere", "ambiente cosmopolita", "a feeling created by people and influences from many different countries"],
  ["quiet and peaceful", "tranquilo y apacible", "calm and without much noise or disturbance"],
  ["full of life", "lleno de vida", "very lively, energetic and active"],
  ["attraction", "atracción / lugar de interés", "a place or feature that visitors want to see"],
  ["park", "parque", "a public green area for recreation"],
  ["temple", "templo", "a building used for religious worship"],
  ["mosque", "mezquita", "a building where Muslims worship"],
  ["art gallery", "galería de arte", "a place where works of art are displayed"],
  ["museum", "museo", "a building where objects of historical, scientific or artistic interest are displayed"],
  ["ruined castle", "castillo en ruinas", "the remains of a castle that has been damaged or partly destroyed"],
  ["housing estate", "urbanización / conjunto residencial", "a large planned group of houses or flats"],
  ["industrial estate", "polígono industrial", "an area containing factories and industrial businesses"],
  ["business district", "distrito financiero / empresarial", "the part of a city where many offices and companies are located"],
  ["residential area", "zona residencial", "an area mainly containing homes"],
  ["outskirts", "afueras", "the outer areas of a town or city"],
  ["suburbs", "barrios periféricos / suburbios", "residential areas on the edge of a city"],
  ["office block", "bloque de oficinas", "a large building containing many offices"],
  ["shopping mall", "centro comercial", "a large enclosed area containing many shops"],
  ["multi-storey car park", "aparcamiento de varias plantas", "a car park built on several levels"],
  ["neglected", "descuidado / deteriorado", "not given enough care or attention"],
  ["bus / cycle lane", "carril bus / bici", "a road lane reserved for buses / a lane reserved for bicycles"],
  ["on the edge of the city", "en el límite de la ciudad", "at or near the outer boundary of a city"],
  ["crowded", "abarrotado", "full of many people with little free space"],
  ["well looked after", "bien cuidado", "kept in good condition through regular care"],
  ["leisure centre", "centro de ocio / deportivo", "a public building with sports and recreation facilities"],
  ["health centre", "centro de salud", "a local place providing medical and health services"],
  ["car park", "aparcamiento", "an area where cars can be left"],
  ["concert hall", "sala de conciertos", "a building designed for live music performances"],
  ["football stadium", "estadio de fútbol", "a large sports venue where football matches are played"],
  ["ice rink", "pista de hielo", "a specially prepared surface for skating on ice"],
  ["bowling alley", "bolera", "a place where the sport of bowling is played"],
  ["shopping centre", "centro comercial", "an area or building containing many shops"],
  ["recreation ground", "zona / campo recreativo", "an outdoor public area used for sport and leisure"],
  ["cellar", "bodega / sótano", "a room below ground level, often used for storage"],
  ["basement", "sótano", "the lowest floor of a building, partly or fully below ground"],
  ["loft", "desván", "a space or room directly under a roof"],
  ["lounge", "salón", "a comfortable room in a home used for relaxing"],
  ["mansion", "mansión", "a very large and impressive house"],
  ["staircase", "escalera", "a set of stairs and its supporting structure inside a building"],
  ["flowerbed", "parterre / macizo de flores", "an area of ground where flowers are planted"],
  ["hedge", "seto", "a line of bushes or small trees forming a boundary"],
  ["fence", "valla", "a structure forming a boundary around an area"],
  ["shutters", "contraventanas / persianas exteriores", "movable covers fixed outside or inside windows"],
  ["curtains", "cortinas", "pieces of cloth hung at windows for privacy or decoration"],
  ["carpet", "moqueta / alfombra", "a thick floor covering made of fabric"],
  ["shed", "cobertizo", "a small simple building used for storage or work"],
  ["lobby", "vestíbulo", "an entrance area inside a building"],
  ["garage", "garaje", "a building or room where a car is kept"],
  ["chimney", "chimenea", "a vertical structure that carries smoke out of a building"],
  ["gate", "portal / verja", "a movable barrier controlling an entrance through a fence or wall"],
  ["terrace", "terraza / patio elevado", "a flat outdoor area beside or on a building"],
  ["cement", "cemento", "a powder used with water and other materials to make concrete"],
  ["wood", "madera", "the hard material from trees used for building and making objects"],
  ["bricks", "ladrillos", "rectangular blocks used for building walls"],
  ["wardrobe", "armario", "a tall piece of furniture used for hanging clothes"],
  ["flat [BrE] / apartment [AmE]", "piso / apartamento", "a set of rooms used as a home in British English / the usual American English word for the same type of home"],
  ["routine chores", "tareas rutinarias", "regular household jobs that need to be done"],
  ["manicured hedge", "seto perfectamente recortado", "a hedge that has been carefully cut and maintained"],
  ["yield", "rendimiento / producción de una cosecha", "the amount of crops or produce obtained from land or plants"],
  ["oak", "roble", "a large tree that produces acorns"],
  ["vow", "prometer solemnemente", "to make a serious or formal promise"],
  ["sensitive issue / word", "tema / palabra delicado", "a subject likely to upset people / a word requiring care because it may cause offence or discomfort"],
  ["builder", "constructor / albañil", "a person whose job is constructing or repairing buildings"],
  ["decorator", "pintor-decorador", "a person whose job is painting and decorating buildings"],
  ["electrician", "electricista", "a person who installs and repairs electrical systems"],
  ["plumber", "fontanero", "a person who installs and repairs water pipes and related equipment"],
  ["service agent", "técnico / servicio de reparación", "a person or company authorised to repair or maintain equipment"],
  ["a dripping tap", "un grifo que gotea", "a tap from which water falls in small drops"],
  ["a leaking pipe", "una tubería con fuga", "a pipe that is allowing water or another liquid to escape"],
  ["kitchen sink", "fregadero", "the basin in a kitchen used for washing dishes and food"],
  ["install lighting", "instalar iluminación", "to fit lights and electrical lighting equipment"],
  ["dishwasher", "lavavajillas", "a machine that washes dishes automatically"],
  ["break down", "averiarse", "to stop working because of a mechanical or technical problem"],
  ["be under guarantee", "estar en garantía", "to be covered by a promise that a product will be repaired or replaced"],
  ["make a patio", "hacer un patio", "to build an outdoor paved area beside a house"],
  ["have a room painted", "hacer pintar una habitación", "to arrange for someone else to paint a room"],
  ["outfit", "conjunto / atuendo", "a set of clothes worn together"],
  ["knee-length", "hasta la rodilla", "reaching as far down as the knees"],
  ["silk dress", "vestido de seda", "a dress made from silk"],
  ["sleeveless", "sin mangas", "made without sleeves"],
  ["V-neck", "cuello de pico", "a neckline shaped like the letter V"],
  ["necklace", "collar", "a piece of jewellery worn around the neck"],
  ["earrings", "pendientes", "pieces of jewellery worn on the ears"],
  ["sandals", "sandalias", "open shoes held on the feet by straps"],
  ["high heels", "tacones altos", "women's shoes with raised heels"],
  ["jeans", "vaqueros", "trousers made from denim"],
  ["straight legs", "pernera recta", "trouser legs that stay roughly the same width from thigh to ankle"],
  ["plain T-shirt", "camiseta lisa", "a T-shirt with no pattern or decoration"],
  ["leather jacket", "chaqueta de cuero", "a jacket made from leather"],
  ["material", "material / tejido", "the substance or fabric from which something is made"],
  ["fit well", "quedar bien de talla", "to be the correct size and shape for a person"],
  ["match", "combinar", "to look good together because colours or styles are suitable"],
  ["suit someone", "sentar / favorecer a alguien", "to make someone look attractive or appropriate"],
  ["get dressed", "vestirse", "to put clothes on your body"],
  ["put your clothes on", "ponerse la ropa", "to place clothes on your body"],
  ["dress smartly", "vestir elegante", "to wear neat or formal clothes"],
  ["wear smart clothes", "llevar ropa elegante", "to have neat or formal clothes on your body"],
  ["be dressed in black", "ir vestido de negro", "to be wearing black clothes"],
  ["be wearing black", "llevar negro", "to have black clothes on"],
  ["get undressed", "desvestirse", "to remove your clothes"],
  ["take off your clothes", "quitarse la ropa", "to remove clothes from your body"],
  ["have shoes on", "llevar zapatos puestos", "to be wearing shoes"],
  ["wear shoes", "llevar zapatos", "to have shoes on your feet"],
  ["wear off", "desaparecer gradualmente (una sensación / interés)", "to gradually disappear or become weaker"],
  ["be worn out", "estar gastado por el uso", "to be damaged or no longer useful because of heavy use"],
  ["wear someone out", "agotar a alguien", "to make someone extremely tired"],
  ["air conditioning", "aire acondicionado", "a system that cools and controls the air inside a building"],
  ["armchair", "sillón", "a comfortable chair with supports for the arms"],
  ["bookcase / shelves", "librería / estanterías", "a piece of furniture for storing books / flat surfaces used for storing or displaying things"],
  ["heating", "calefacción", "a system used to make a building warm"],
  ["chest of drawers", "cómoda", "a piece of furniture with several drawers for storing clothes or other items"],
  ["computer", "ordenador", "an electronic machine used to process, store and display information"],
  ["cushion", "cojín", "a soft bag filled with material and used for comfort or decoration"],
  ["desk", "escritorio", "a table used for studying, writing or working"],
  ["duvet", "edredón", "a thick soft covering used on a bed"],
  ["lamp", "lámpara", "a device that produces light"],
  ["mirror", "espejo", "a surface that reflects an image"],
  ["pictures / posters", "cuadros / pósteres", "images displayed as decoration / large printed pictures displayed on walls"],
  ["a safe haven", "un refugio seguro", "a place where you feel protected and comfortable"],
  ["dimly lit", "con luz tenue", "having only a small amount of light"],
  ["restful", "relajante / que da descanso", "making you feel calm and rested"],
  ["escape the stresses of daily life", "escapar del estrés diario", "to get temporary relief from everyday pressures"],
  ["bug someone", "molestar a alguien", "to annoy or irritate someone"],
  ["calm and quiet", "tranquilo y silencioso", "peaceful and without much noise"],
  ["take a nap", "echarse una siesta", "to sleep for a short period during the day"],
  ["messy", "desordenado", "untidy and not well organised"],
  ["tidy up", "ordenar", "to make a place neat by putting things in the correct places"],
  ["hang out", "pasar el rato", "to spend time relaxing or socialising informally"],
  ["mates", "colegas / amigos", "friends, especially in informal British English"],
  ["within easy reach", "al alcance de la mano", "close enough to reach or access easily"],
  ["throw out", "tirar / deshacerse de", "to get rid of something that is no longer wanted"],
];
