import type { VocabularyGloss } from "./glosses";

export const studyWorkGlosses: VocabularyGloss[] = [
  ["primary school", "escuela primaria", "a school for young children before secondary education"],
  ["secondary school", "instituto / secundaria", "a school for students after primary education"],
  ["state school", "centro público", "a school funded by the government"],
  ["streamed classes", "clases agrupadas por nivel", "classes organised according to students' ability levels"],
  ["comprehensive school", "centro no selectivo", "a secondary school that accepts students of all ability levels"],
  ["private school", "centro privado", "a school funded mainly by fees rather than the government"],
  ["kindergarten / nursery school", "escuela infantil", "a school or class for very young children / a school for children before primary education"],
  ["further education college", "centro de formación postobligatoria", "an institution providing education after compulsory school, often vocational or academic"],
  ["canteen", "comedor / cafetería escolar", "a place in a school or workplace where meals are served"],
  ["laboratory", "laboratorio", "a room equipped for scientific experiments or practical work"],
  ["library", "biblioteca", "a place where books and other resources can be read or borrowed"],
  ["classroom", "aula", "a room where students are taught"],
  ["gym", "gimnasio", "a room or building used for exercise and physical education"],
  ["playing fields", "campos deportivos", "outdoor areas used for sports at a school"],
  ["teacher", "profesor de colegio", "a person who teaches students, especially at school"],
  ["principal / head", "director del centro", "the person in charge of a school / the person who leads a school"],
  ["teaching assistant", "auxiliar docente", "a person who supports a teacher and helps students in class"],
  ["lecturer", "profesor universitario", "a person who teaches at a university or college"],
  ["class", "clase", "a group of students taught together, or a period of teaching"],
  ["curriculum", "currículo / plan de estudios", "the subjects and content taught by a school or course"],
  ["timetable", "horario", "a schedule showing when classes or activities take place"],
  ["uniform", "uniforme", "a standard set of clothes worn by members of a school or organisation"],
  ["subject", "asignatura", "an area of knowledge studied at school or university"],
  ["compulsory", "obligatorio", "required by a rule or law"],
  ["pupil", "alumno de colegio", "a child or young person who is taught at school"],
  ["homework", "deberes", "school work that students must do at home"],
  ["project", "proyecto", "a piece of planned work carried out over a period of time"],
  ["deadline", "fecha límite", "the latest time or date by which something must be completed"],
  ["vocational course", "curso profesional / FP", "a course that prepares students for a particular job or practical career"],
  ["opportunity", "oportunidad", "a situation that makes it possible to do something useful or desirable"],
  ["be at school", "estar escolarizado / en el colegio", "to be attending school as a student"],
  ["start primary school", "empezar primaria", "to begin attending primary school"],
  ["attend a school", "asistir a un centro", "to go regularly to a particular school"],
  ["be taught by", "ser enseñado por", "to receive instruction from a particular person"],
  ["miss a deadline", "no cumplir una fecha límite", "to fail to complete something by the required time"],
  ["stay after school", "quedarse después de clase", "to remain at school after normal lessons have finished"],
  ["hand work in", "entregar un trabajo", "to give completed work to a teacher for assessment"],
  ["be allowed to", "tener permiso para", "to have permission to do something"],
  ["take an exam", "hacer / presentarse a un examen", "to sit and complete an examination"],
  ["leave school", "terminar / dejar los estudios escolares", "to stop attending school, usually after completing compulsory education"],
  ["stay on", "continuar estudiando en el mismo centro", "to continue studying at a school after the usual leaving age"],
  ["study subjects", "estudiar asignaturas", "to learn particular areas of knowledge"],
  ["English", "inglés", "the English language as a school subject"],
  ["art", "arte", "the study or practice of creating visual work"],
  ["business studies", "empresa / estudios empresariales", "the study of how businesses are organised and managed"],
  ["drama", "teatro", "the study or practice of acting and plays"],
  ["computing", "informática", "the study and use of computers and computer systems"],
  ["geography", "geografía", "the study of places, environments and the Earth's surface"],
  ["history", "historia", "the study of past events"],
  ["literature", "literatura", "the study of written works such as novels, poems and plays"],
  ["maths", "matemáticas", "the study of numbers, quantities and shapes"],
  ["music", "música", "the study or practice of music"],
  ["psychology", "psicología", "the scientific study of the mind and behaviour"],
  ["science", "ciencias", "the systematic study of the natural world through observation and experiment"],
  ["physical education", "educación física", "school lessons involving sport, exercise and physical activity"],
  ["use my imagination", "usar mi imaginación", "to form ideas or images creatively in your mind"],
  ["be better with numbers than words", "ser mejor con números que con palabras", "to find numerical tasks easier than language-based ones"],
  ["be good at", "ser bueno en", "to have skill or ability in a particular activity or subject"],
  ["do practical things", "hacer cosas prácticas", "to carry out hands-on activities rather than only theoretical work"],
  ["find a subject stimulating", "encontrar una asignatura estimulante", "to consider a subject interesting and mentally engaging"],
  ["work in groups", "trabajar en grupos", "to complete tasks together with other students"],
  ["do / take an exam", "hacer / presentarse a un examen", "to sit an examination / to sit an examination"],
  ["revise for an exam", "repasar para un examen", "to study material again in preparation for an examination"],
  ["retake an exam", "volver a hacer un examen", "to take an examination again after a previous attempt"],
  ["pass an exam", "aprobar", "to achieve the required result in an examination"],
  ["fail an exam", "suspender", "to not achieve the required result in an examination"],
  ["give a subject up", "dejar una asignatura", "to stop studying a subject"],
  ["study a subject", "estudiar una asignatura", "to learn about a particular academic subject"],
  ["be entered for an exam", "estar inscrito para un examen", "to be officially registered to take an examination"],
  ["hairdresser", "peluquero", "a person whose job is cutting and styling hair"],
  ["carpenter", "carpintero", "a person who makes or repairs wooden objects and structures"],
  ["accountant", "contable", "a professional who prepares and checks financial records"],
  ["architect", "arquitecto", "a professional who designs buildings"],
  ["builder", "constructor / albañil", "a person whose job involves constructing or repairing buildings"],
  ["cleaner", "personal de limpieza", "a person whose job is cleaning buildings or rooms"],
  ["mechanic", "mecánico", "a person who repairs machines or vehicles"],
  ["nursery assistant", "auxiliar de guardería", "a person who helps care for and educate young children in a nursery"],
  ["receptionist", "recepcionista", "a person who greets visitors and deals with calls and appointments"],
  ["sales manager", "responsable de ventas", "a person responsible for managing a company's sales activity"],
  ["cheerful", "alegre", "noticeably happy and positive"],
  ["friendly", "amable", "kind and pleasant towards other people"],
  ["physically fit", "en buena forma física", "healthy and strong enough for physical activity"],
  ["good with your hands", "habilidoso con las manos", "skilled at making or repairing things manually"],
  ["creative", "creativo", "able to produce original and imaginative ideas"],
  ["efficient", "eficiente", "working well without wasting time, energy or resources"],
  ["well-organised", "organizado", "good at planning and arranging tasks effectively"],
  ["self-motivated", "automotivado", "able to work hard without needing other people to encourage you"],
  ["able to work without supervision", "capaz de trabajar sin supervisión", "capable of working independently without someone watching or directing you"],
  ["good communication skills", "buenas habilidades comunicativas", "the ability to express ideas clearly and interact effectively with people"],
  ["reliable", "fiable", "able to be trusted to do what is expected"],
  ["flexible", "flexible", "willing and able to adapt to different situations or working arrangements"],
  ["honest", "honesto", "truthful and not likely to cheat or deceive"],
  ["hard-working", "trabajador", "putting a lot of effort into work"],
  ["enthusiastic", "entusiasta", "showing strong interest and excitement"],
  ["caring", "atento / cariñoso", "kind and concerned about other people's needs"],
  ["temporary job", "trabajo temporal", "a job that lasts for a limited period"],
  ["permanent job", "trabajo fijo", "a job with no planned end date"],
  ["promotion", "ascenso", "a move to a more senior or better-paid position"],
  ["shift work", "trabajo por turnos", "work organised into different periods of the day or night"],
  ["overtime", "horas extra", "time worked beyond normal working hours"],
  ["application form", "formulario de solicitud", "a document used to apply for a job, course or service"],
  ["job description", "descripción del puesto", "a document describing the duties and responsibilities of a job"],
  ["qualifications", "titulaciones / cualificaciones", "official achievements showing education, training or skills"],
  ["experience", "experiencia", "knowledge or skill gained by doing something over time"],
  ["training", "formación", "the process of learning the skills needed for a job"],
  ["vacancy", "vacante", "an available job position"],
  ["reference", "referencia laboral", "a statement or contact that confirms a person's suitability for a job"],
  ["catering industry", "sector de hostelería / restauración", "the business sector that provides food and drink for customers or events"],
  ["salary", "sueldo anual fijo, normalmente pagado mensualmente", "a fixed amount of money paid for work, usually expressed yearly and paid monthly"],
  ["wages", "salario normalmente semanal", "money paid for work, often calculated hourly or weekly"],
  ["rate of pay", "cantidad pagada por hora", "the amount of money paid for each hour or unit of work"],
  ["recent → recently", "reciente → recientemente", "happening a short time ago → a short time ago"],
  ["vacant → vacancy", "vacante adj. → vacante sust.", "available and not occupied → an available job or position"],
  ["apply → application", "solicitar → solicitud", "to formally ask for something → a formal request for something"],
  ["cater → catering", "servir comida / atender → hostelería", "to provide food or meet particular needs → the business of providing food and drink"],
  ["passion → passionate", "pasión → apasionado", "a very strong interest or feeling → showing very strong interest or enthusiasm"],
  ["profession → professional", "profesión → profesional", "a skilled occupation requiring training → relating to work or showing high standards at work"],
  ["rely → reliable", "depender / confiar → fiable", "to depend on or trust someone or something → able to be trusted"],
  ["train → training", "formar → formación", "to teach skills needed for a job → the process of learning those skills"],
  ["enthusiasm → enthusiastic", "entusiasmo → entusiasta", "strong interest and excitement → showing strong interest and excitement"],
  ["refer → reference", "referir → referencia", "to mention or direct attention to something → information or a recommendation used to support an application"],
  ["work [U]", "trabajo en general / actividad laboral", "work considered as an activity in general"],
  ["job [C]", "puesto de trabajo concreto", "a particular paid position of employment"],
  ["career [C]", "trayectoria profesional", "the series of jobs and professional development in a person's working life"],
  ["occupation", "ocupación; término formal típico de formularios", "a person's job or regular type of work, especially in formal contexts"],
  ["resign", "dimitir", "to formally leave a job or position"],
  ["give up a job", "dejar un trabajo", "to stop doing a particular job"],
  ["be made redundant", "ser despedido por amortización del puesto", "to lose a job because the position is no longer needed"],
  ["be out of work", "estar desempleado", "to be unemployed"],
  ["work experience", "experiencia laboral / prácticas", "experience gained by spending time in a workplace, often as part of education"],
  ["be promoted", "ser ascendido", "to be moved to a more senior position at work"],
  ["change career", "cambiar de carrera profesional", "to move from one professional field to another"],
  ["apply for a job", "solicitar un puesto", "to formally ask to be considered for a job"],
  ["campus", "campus", "the buildings and grounds of a university or college"],
  ["faculty", "facultad", "a university division covering a related group of academic subjects"],
  ["department", "departamento", "an academic division within a university or faculty"],
  ["prospectus", "folleto informativo universitario", "an official document giving information about a school, college or university"],
  ["lecture", "clase magistral", "a formal talk given to a group of university students"],
  ["seminar", "seminario", "a class where a small group discusses a subject in detail"],
  ["tutorial", "tutoría", "a teaching session involving an individual student or a small group"],
  ["lecturer", "profesor universitario", "a person who teaches at a university or college"],
  ["tutor", "tutor", "a teacher who gives individual or small-group academic guidance"],
  ["halls of residence", "residencia universitaria", "university buildings where students live"],
  ["students’ union", "asociación / centro de estudiantes", "an organisation representing students and often providing social facilities"],
  ["mature student", "estudiante adulto (21+ en el contexto británico del libro)", "an adult student who begins higher education later than the usual age"],
  ["term", "trimestre / periodo académico", "one of the main periods into which an academic year is divided"],
  ["semester", "semestre", "one of two main periods into which an academic year is often divided"],
  ["vacation", "vacaciones académicas", "a period when university teaching stops and students are on holiday"],
  ["undergraduate", "estudiante de grado", "a university student studying for a first degree"],
  ["graduate", "graduado", "a person who has completed a university degree"],
  ["postgraduate", "estudiante de posgrado", "a student doing advanced study after a first degree"],
  ["architecture", "arquitectura", "the study and design of buildings"],
  ["English literature", "literatura inglesa", "the study of literary works written in English"],
  ["biology", "biología", "the scientific study of living things"],
  ["law", "derecho", "the study of legal rules and systems"],
  ["psychology", "psicología", "the scientific study of the mind and behaviour"],
  ["history", "historia", "the study of past events"],
  ["economics", "economía", "the study of how money, resources and markets work"],
  ["chemistry", "química", "the science of substances and how they change or react"],
  ["medicine", "medicina", "the study and practice of preventing and treating illness"],
  ["essay", "ensayo corto académico", "a relatively short piece of academic writing on a particular subject"],
  ["assignment", "trabajo / tarea académica", "a piece of work that a student is required to complete"],
  ["experiment", "experimento", "a scientific test carried out to discover or demonstrate something"],
  ["dissertation", "trabajo extenso normalmente exigido en un grado", "a long piece of academic writing, often required for a degree"],
  ["presentation", "presentación", "a talk in which information or ideas are explained to an audience"],
  ["thesis", "tesis de investigación, normalmente para un grado superior", "an extended piece of original research written for an advanced degree"],
  ["essay", "texto relativamente corto sobre un tema", "a relatively short piece of writing about a subject"],
  ["dissertation", "trabajo mucho más largo, a menudo requisito de un grado", "a much longer academic work, often required for a degree"],
  ["thesis", "investigación extensa para un título superior", "a substantial piece of research written for an advanced qualification"],
  ["I’m really enthusiastic about ...", "Estoy muy entusiasmado con...", "a phrase used to express very strong positive interest in something"],
  ["be totally against ...", "estar totalmente en contra de...", "to strongly oppose an idea, plan or action"],
  ["in my view", "en mi opinión", "a phrase used to introduce your personal opinion"],
  ["approve of", "aprobar / estar de acuerdo con", "to think that something is good, acceptable or right"],
  ["I personally think ...", "personalmente pienso...", "a phrase used to emphasise that you are giving your own opinion"],
  ["I believe ...", "creo...", "a phrase used to state an opinion or belief"],
  ["I’m convinced that ...", "estoy convencido de que...", "a phrase used to express a very strong belief that something is true"],
  ["I really appreciate ...", "valoro mucho...", "a phrase used to express that you value something highly"],
  ["I’m in favour of ...", "estoy a favor de...", "a phrase used to show that you support an idea or proposal"],
  ["think through the implications", "analizar bien las implicaciones", "to consider all the possible results or consequences carefully"],
  ["think it over", "pensarlo detenidamente", "to consider something carefully before deciding"],
  ["think straight", "pensar con claridad", "to think clearly and logically"],
  ["think back to", "recordar / pensar en un momento pasado", "to remember and mentally return to a past time or event"],
  ["not think twice about doing something", "hacer algo sin dudarlo", "to do something immediately without hesitation"],
];
