import type { VocabularyGloss } from "./glosses";

export const timeGlosses: VocabularyGloss[] = [
  ["tomb", "tumba", "a place where a dead person is buried, often in a stone structure"],
  ["man-made structure", "estructura construida por el ser humano", "a building or object created by people rather than by nature"],
  ["remain intact", "permanecer intacto", "to stay complete and undamaged"],
  ["ancient site", "yacimiento / lugar antiguo", "a place from a very old period that has historical or archaeological importance"],
  ["archaeologist", "arqueólogo", "a person who studies past human life by examining physical remains"],
  ["temple", "templo", "a building used for religious worship"],
  ["archaeological evidence", "evidencia arqueológica", "physical remains or findings that support ideas about the past"],
  ["prehistory", "prehistoria", "the period before written records existed"],
  ["written records", "registros escritos", "documents that preserve information about past events"],
  ["population", "población", "all the people living in a particular area"],
  ["precise figures", "cifras precisas", "exact numerical information"],
  ["inhabitants", "habitantes", "people who live in a particular place"],
  ["tribe", "tribu", "a social group whose members share culture, ancestry or traditions"],
  ["ancestor", "antepasado", "a person in your family who lived many generations ago"],
  ["hunting", "caza", "the activity of finding and killing wild animals for food or sport"],
  ["gathering", "recolección", "the activity of collecting food or materials from nature"],
  ["settle down", "establecerse", "to begin living permanently in one place"],
  ["farming techniques", "técnicas agrícolas", "methods used for growing crops or raising animals"],
  ["grow crops", "cultivar", "to produce plants for food or other uses"],
  ["tool", "herramienta", "an object used to perform a particular task"],
  ["belief", "creencia", "an idea that someone accepts as true"],
  ["story", "historia / relato", "an account of real or imagined events"],
  ["history", "los acontecimientos del pasado / su estudio", "past events considered together, or the study of those events"],
  ["story", "relato real o imaginado; también noticia", "an account of events that may be real or invented"],
  ["history → historian → historical / historic", "historia → historiador → histórico (relacionado con historia) / histórico (importante)", "the study or record of the past → a person who studies history → relating to the past / important in history"],
  ["prehistory → prehistoric", "prehistoria → prehistórico", "the period before written records → belonging to that period"],
  ["archaeology → archaeologist → archaeological", "arqueología → arqueólogo → arqueológico", "the study of past societies through remains → a specialist in that study → relating to archaeology"],
  ["evidence → evident", "evidencia → evidente", "facts or signs that show something is true → clear and easy to see or understand"],
  ["politics → politician → political", "política → político → político", "activities connected with government → a person involved in politics → relating to politics"],
  ["presidency → president → presidential", "presidencia → presidente → presidencial", "the position or period of being president → the person who holds that office → relating to a president"],
  ["populate → population", "poblar → población", "to live in or fill an area with people → all the people living in an area"],
  ["civilise → civilisation / civilian", "civilizar → civilización / civil", "to develop an organised society → an advanced human society / a person who is not in the armed forces"],
  ["invade → invasion / invader", "invadir → invasión / invasor", "to enter a country by force → the act of doing so / a person or force that does so"],
  ["reside → residence / resident", "residir → residencia / residente", "to live in a place → the place or fact of living there / a person who lives there"],
  ["believe → belief / believer", "creer → creencia / creyente", "to accept something as true → an idea accepted as true / a person who believes"],
  ["survive → survival / survivor", "sobrevivir → supervivencia / superviviente", "to remain alive after danger or difficulty → the act of staying alive / a person who survives"],
  ["historic", "importante o destinado a ser importante en la historia", "important in history or likely to be remembered as historically important"],
  ["historical", "relacionado con el estudio o representación del pasado", "connected with the past or with the study of history"],
  ["last", "durar", "to continue for a particular length of time"],
  ["pass", "pasar / transcurrir el tiempo", "to move forward as time goes by"],
  ["spend time", "pasar / dedicar tiempo haciendo algo", "to use a period of time doing something"],
  ["take time", "necesitar / llevar cierta cantidad de tiempo", "to require a particular amount of time"],
  ["on time", "puntual; ni pronto ni tarde", "at the planned or correct time"],
  ["for some time", "durante bastante tiempo", "for a fairly long period"],
  ["in no time", "enseguida", "very quickly or after only a short period"],
  ["from time to time", "de vez en cuando", "occasionally"],
  ["have no time for someone", "no tener paciencia / respeto por alguien", "to have little patience, interest or respect for someone"],
  ["make time for", "sacar tiempo para", "to arrange your schedule so that you can do something"],
  ["kill time", "matar el tiempo", "to do something unimportant while waiting"],
  ["take your time", "tomarse el tiempo necesario / sin prisa", "to do something without hurrying"],
];
