import type { VocabularyGloss } from "./glosses";

export const worldGlosses: VocabularyGloss[] = [
  ["peak", "pico de montaña", "the highest point of a mountain"],
  ["pine", "pino", "an evergreen tree with thin needle-shaped leaves"],
  ["stream", "arroyo", "a small narrow river"],
  ["vegetation", "vegetación", "plants considered together in a particular area"],
  ["slope", "pendiente / ladera", "a surface of land that goes up or down at an angle"],
  ["orchard", "huerto de árboles frutales", "an area of land where fruit trees are grown"],
  ["track", "sendero / pista", "a path or rough road, often through the countryside"],
  ["valley", "valle", "a low area of land between hills or mountains"],
  ["bank", "orilla de un río", "the land along the side of a river"],
  ["spring", "manantial", "a place where water naturally comes out of the ground"],
  ["jungle / rainforest", "selva / bosque tropical", "a dense tropical area of wild vegetation / a tropical forest with very heavy rainfall"],
  ["trunk", "tronco", "the main thick stem of a tree"],
  ["sunlight", "luz solar", "natural light that comes from the sun"],
  ["plant", "planta", "a living organism that grows in soil and usually has leaves and roots"],
  ["leaf / leaves", "hoja / hojas", "a flat green part that grows from a plant or tree / the plural form of leaf"],
  ["soil", "suelo / tierra", "the top layer of earth in which plants grow"],
  ["root", "raíz", "the part of a plant that grows underground and takes in water"],
  ["branch", "rama", "a part of a tree that grows out from the trunk"],
  ["insect", "insecto", "a small animal with six legs and usually one or two pairs of wings"],
  ["butterfly", "mariposa", "an insect with large colourful wings"],
  ["wildlife", "fauna y vida silvestre", "animals and plants living naturally in the wild"],
  ["shallow ↔ deep", "poco profundo ↔ profundo", "not having much distance from top to bottom ↔ having a large distance from top to bottom"],
  ["narrow ↔ wide", "estrecho ↔ ancho", "having little distance from side to side ↔ having a large distance from side to side"],
  ["winding ↔ straight", "sinuoso ↔ recto", "following many curves ↔ continuing in one direct line"],
  ["clear ↔ muddy", "claro / limpio ↔ embarrado / turbio", "easy to see through or free from dirt ↔ containing mud or looking dirty"],
  ["wild ↔ cultivated", "salvaje ↔ cultivado", "growing naturally without human control ↔ prepared and used for growing crops or plants"],
  ["flat ↔ mountainous", "llano ↔ montañoso", "level and without hills ↔ containing many mountains"],
  ["gentle ↔ steep", "suave (pendiente) ↔ empinado", "rising or falling gradually ↔ rising or falling at a sharp angle"],
  ["hot and humid", "caluroso y húmedo", "having high temperatures and a lot of moisture in the air"],
  ["mild and wet", "suave y lluvioso / húmedo", "not very hot or cold and receiving a lot of rain"],
  ["the Equator", "el ecuador", "the imaginary line around the middle of the Earth"],
  ["dry season", "estación seca", "the part of the year when very little rain falls"],
  ["wet season", "estación lluviosa", "the part of the year when most rain falls"],
  ["frosty", "con heladas", "extremely cold with frost on the ground or surfaces"],
  ["below zero", "bajo cero", "at a temperature lower than zero degrees"],
  ["dawn breaks", "amanece", "the first light of day appears"],
  ["the sun comes up", "sale el sol", "the sun rises above the horizon"],
  ["clear blue sky", "cielo azul despejado", "a blue sky with no clouds"],
  ["heavy snowfall", "fuerte nevada", "a large amount of snow falling"],
  ["pour with rain", "llover a cántaros", "to rain very heavily"],
  ["thunderstorm", "tormenta eléctrica", "a storm with thunder, lightning and usually heavy rain"],
  ["be cut off by snow", "quedar incomunicado por la nieve", "to become impossible to reach because snow blocks the routes"],
  ["flood", "inundación", "a large amount of water covering land that is normally dry"],
  ["cloudy", "nublado", "covered with or containing many clouds"],
  ["temperature", "temperatura", "a measure of how hot or cold something is"],
  ["warmest / coolest month", "mes más cálido / más fresco", "the month with the highest average temperature / the month with the lowest or mildest average temperature"],
  ["weather forecast", "previsión meteorológica", "a report predicting what the weather will be like"],
  ["freeze → frozen", "congelar → congelado", "to become or make something extremely cold and solid → made solid by very low temperatures"],
  ["mist → misty", "niebla → brumoso", "a thin cloud of tiny water drops near the ground → covered with or full of mist"],
  ["storm → stormy", "tormenta → tormentoso", "a period of violent weather → having strong winds, rain or storms"],
  ["tropic → tropical", "trópico → tropical", "a region near the Equator → relating to hot regions near the Equator"],
  ["warm → warmth", "cálido → calor", "having a comfortably high temperature → the state or quality of being warm"],
  ["globe → global", "globo / mundo → global", "the world or a model of it → relating to the whole world"],
  ["a mountain of work", "una enorme cantidad de trabajo", "a very large amount of work"],
  ["a flood of applications", "una avalancha de solicitudes", "a very large number of applications arriving at the same time"],
  ["make observations", "hacer observaciones", "to watch or study something carefully and record what you notice"],
  ["enter data into a computer", "introducir datos en un ordenador", "to put information into a computer system"],
  ["collect data", "recoger datos", "to gather information for study or analysis"],
  ["make exciting discoveries", "hacer descubrimientos importantes / emocionantes", "to find new and interesting facts or things"],
  ["do experiments", "hacer experimentos", "to carry out scientific tests"],
  ["make predictions", "hacer predicciones", "to state what you think will happen in the future"],
  ["attend conferences", "asistir a congresos", "to go to organised professional or academic meetings"],
  ["interpret statistics", "interpretar estadísticas", "to explain what numerical data means"],
  ["work as part of a team", "trabajar como parte de un equipo", "to cooperate with other people in a group"],
  ["astronomer → astronomy → astronomical", "astrónomo → astronomía → astronómico", "a scientist who studies space → the scientific study of space → relating to astronomy"],
  ["biologist → biology → biological", "biólogo → biología → biológico", "a scientist who studies living things → the study of living things → relating to biology"],
  ["chemist → chemistry → chemical", "químico → química → químico", "a scientist who studies substances → the science of substances and reactions → relating to chemistry or a substance used in chemistry"],
  ["ecologist → ecology → ecological", "ecólogo → ecología → ecológico", "a scientist who studies relationships in nature → the study of those relationships → relating to ecology"],
  ["geologist → geology → geological", "geólogo → geología → geológico", "a scientist who studies rocks and the Earth → the study of the Earth's physical structure → relating to geology"],
  ["mathematician → mathematics / maths → mathematical", "matemático → matemáticas → matemático", "a person who studies mathematics → the study of numbers, quantities and shapes / the short form of mathematics → relating to mathematics"],
  ["physicist → physics → physical", "físico → física → físico", "a scientist who studies physics → the science of matter, energy and forces → relating to physics or the body"],
  ["global warming", "calentamiento global", "the long-term rise in the Earth's average temperature"],
  ["heavy traffic", "tráfico intenso", "a large amount of traffic causing slow movement or congestion"],
  ["exhaust fumes", "gases de escape", "waste gases produced by vehicle engines"],
  ["emissions", "emisiones", "gases or substances released into the air"],
  ["chemicals used on crops", "productos químicos usados en cultivos", "chemical substances applied to plants grown for food"],
  ["acid rain", "lluvia ácida", "rain made unusually acidic by air pollution"],
  ["rising water levels", "subida del nivel del agua", "water levels that are becoming higher"],
  ["flooding", "inundaciones", "the covering of normally dry land by water"],
  ["household waste", "residuos domésticos", "rubbish produced by homes"],
  ["rubbish dump", "vertedero", "a place where waste is taken and left"],
  ["pollution", "contaminación", "harmful substances that damage air, water or land"],
  ["fossil fuels", "combustibles fósiles", "fuels such as coal, oil and gas formed from ancient organic material"],
  ["carbon dioxide", "dióxido de carbono", "a gas produced naturally and by burning fuels"],
  ["renewable energy resources", "recursos de energía renovable", "energy sources that can be naturally replaced"],
  ["wind energy", "energía eólica", "energy produced from the movement of air"],
  ["solar energy", "energía solar", "energy produced from sunlight"],
  ["asthma sufferer", "persona que padece asma", "a person who has asthma"],
  ["recycle rubbish", "reciclar residuos", "to process waste so that it can be used again"],
  ["switch off electrical equipment", "apagar aparatos eléctricos", "to turn electrical devices off"],
  ["avoid wasting power", "evitar malgastar energía", "to prevent unnecessary use of electricity or energy"],
  ["turn up the heating", "subir la calefacción", "to increase the temperature setting of a heating system"],
  ["organic food", "comida ecológica", "food produced without many artificial chemicals"],
  ["use public transport", "usar transporte público", "to travel by shared services such as buses or trains"],
  ["end up in our food", "acabar en nuestra comida", "to eventually become present in the food we eat"],
  ["contribute to global warming", "contribuir al calentamiento global", "to help cause or increase global warming"],
  ["on record", "registrado / del que hay registro", "officially recorded or documented"],
  ["environmentally friendly", "respetuoso con el medio ambiente", "causing little or no damage to the environment"],
  ["maintain something to a high standard", "mantener algo con un nivel alto", "to keep something at a very good level of quality"],
  ["pollution harms ...", "pollution + harm: la contaminación perjudica...", "a common pattern meaning that pollution damages someone or something"],
  ["spread across boundaries", "extenderse a través de fronteras", "to move or extend beyond borders or limits"],
  ["cause pollution", "causar contaminación", "to produce pollution"],
  ["make a problem worse", "empeorar un problema", "to increase the seriousness of a problem"],
  ["be linked to", "estar relacionado con", "to be connected or associated with something"],
  ["cut down vehicle use", "reducir el uso de vehículos", "to reduce how much vehicles are used"],
];
