import "server-only";
import postgres from "postgres";
import {
  emptyDynamicStudyGroupFilter,
  type DynamicStudyGroupFilter,
  type StudyGroup,
  type VocabularyProgress,
  type VocabularyProgressRecord,
} from "./study-groups";

export type StudyAttemptInput = {
  senseId: string;
  gameType: "multiple-choice" | "flashcards" | "write-word";
  direction: string;
  difficulty?: string | null;
  correct: boolean;
  selectedAnswer?: string | null;
};

export type RemoteStudyState = {
  groups: StudyGroup[];
  progress: VocabularyProgress;
};

const SCHEMA_SQL = `
create table if not exists public.study_groups (
  user_id uuid not null references auth.users(id) on delete cascade,
  id text not null,
  name text not null,
  kind text not null check (kind in ('static', 'dynamic')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

create table if not exists public.study_group_items (
  user_id uuid not null,
  group_id text not null,
  sense_id text not null,
  added_at timestamptz not null default now(),
  primary key (user_id, group_id, sense_id),
  foreign key (user_id, group_id)
    references public.study_groups(user_id, id)
    on delete cascade
);

create table if not exists public.study_group_rules (
  user_id uuid not null,
  group_id text not null,
  rules jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, group_id),
  foreign key (user_id, group_id)
    references public.study_groups(user_id, id)
    on delete cascade
);

create table if not exists public.vocabulary_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sense_id text not null,
  game_type text not null,
  direction text not null,
  difficulty text,
  correct boolean not null,
  selected_answer text,
  created_at timestamptz not null default now()
);

create table if not exists public.vocabulary_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  sense_id text not null,
  attempts integer not null default 0 check (attempts >= 0),
  correct integer not null default 0 check (correct >= 0),
  incorrect integer not null default 0 check (incorrect >= 0),
  streak integer not null default 0 check (streak >= 0),
  last_practised_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, sense_id)
);

create table if not exists public.user_study_migrations (
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  migration_key text not null,
  migrated_at timestamptz not null default now(),
  primary key (user_id, device_id, migration_key)
);

create index if not exists vocabulary_attempts_user_created_idx
  on public.vocabulary_attempts(user_id, created_at desc);
create index if not exists vocabulary_attempts_user_sense_idx
  on public.vocabulary_attempts(user_id, sense_id);

alter table public.study_groups enable row level security;
alter table public.study_group_items enable row level security;
alter table public.study_group_rules enable row level security;
alter table public.vocabulary_attempts enable row level security;
alter table public.vocabulary_progress enable row level security;
alter table public.user_study_migrations enable row level security;

do $$ begin
  create policy study_groups_own on public.study_groups
    for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy study_group_items_own on public.study_group_items
    for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy study_group_rules_own on public.study_group_rules
    for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy vocabulary_attempts_own on public.vocabulary_attempts
    for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy vocabulary_progress_own on public.vocabulary_progress
    for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy user_study_migrations_own on public.user_study_migrations
    for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

grant select, insert, update, delete on public.study_groups to authenticated;
grant select, insert, update, delete on public.study_group_items to authenticated;
grant select, insert, update, delete on public.study_group_rules to authenticated;
grant select, insert, update, delete on public.vocabulary_attempts to authenticated;
grant select, insert, update, delete on public.vocabulary_progress to authenticated;
grant select, insert, update, delete on public.user_study_migrations to authenticated;
grant usage, select on sequence public.vocabulary_attempts_id_seq to authenticated;
`;

let schemaReady: Promise<void> | null = null;
let appSql: ReturnType<typeof postgres> | null = null;

export class StudyDatabaseUnavailableError extends Error {
  constructor() {
    super("The Supabase Postgres connection is not available.");
    this.name = "StudyDatabaseUnavailableError";
  }
}

function connectionString() {
  const value = process.env.POSTGRES_URL?.trim();
  if (!value) throw new StudyDatabaseUnavailableError();
  return value;
}

function migrationConnectionString() {
  return process.env.POSTGRES_URL_NON_POOLING?.trim() || connectionString();
}

function sqlClient() {
  if (!appSql) {
    appSql = postgres(connectionString(), {
      max: 4,
      prepare: false,
      idle_timeout: 20,
      connect_timeout: 15,
    });
  }
  return appSql;
}

export async function ensureStudySchema() {
  if (!schemaReady) {
    schemaReady = (async () => {
      const migrationSql = postgres(migrationConnectionString(), {
        max: 1,
        prepare: false,
        connect_timeout: 20,
      });
      try {
        await migrationSql.unsafe(SCHEMA_SQL);
      } finally {
        await migrationSql.end({ timeout: 5 });
      }
    })().catch((error) => {
      schemaReady = null;
      throw error;
    });
  }

  return schemaReady;
}

function parseFilter(value: unknown): DynamicStudyGroupFilter {
  if (!value) return { ...emptyDynamicStudyGroupFilter };
  if (typeof value === "string") {
    try {
      return JSON.parse(value) as DynamicStudyGroupFilter;
    } catch {
      return { ...emptyDynamicStudyGroupFilter };
    }
  }
  if (typeof value === "object") return value as DynamicStudyGroupFilter;
  return { ...emptyDynamicStudyGroupFilter };
}

function asIso(value: Date | string | null | undefined) {
  if (!value) return "";
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString();
}

export async function getStudyState(userId: string): Promise<RemoteStudyState> {
  await ensureStudySchema();
  const sql = sqlClient();

  const [groups, items, rules, progressRows] = await Promise.all([
    sql<{ id: string; name: string; kind: "static" | "dynamic" }[]>`
      select id, name, kind
      from public.study_groups
      where user_id = ${userId}
      order by created_at asc, id asc
    `,
    sql<{ group_id: string; sense_id: string }[]>`
      select group_id, sense_id
      from public.study_group_items
      where user_id = ${userId}
      order by added_at asc, sense_id asc
    `,
    sql<{ group_id: string; rules: unknown }[]>`
      select group_id, rules
      from public.study_group_rules
      where user_id = ${userId}
    `,
    sql<{
      sense_id: string;
      attempts: number;
      correct: number;
      incorrect: number;
      streak: number;
      last_practised_at: Date | string | null;
    }[]>`
      select sense_id, attempts, correct, incorrect, streak, last_practised_at
      from public.vocabulary_progress
      where user_id = ${userId}
    `,
  ]);

  const itemsByGroup = new Map<string, string[]>();
  for (const item of items) {
    const current = itemsByGroup.get(item.group_id) ?? [];
    current.push(item.sense_id);
    itemsByGroup.set(item.group_id, current);
  }
  const rulesByGroup = new Map(rules.map((rule) => [rule.group_id, parseFilter(rule.rules)]));

  const studyGroups: StudyGroup[] = groups.map((group) => {
    if (group.kind === "static") {
      return {
        id: group.id,
        name: group.name,
        kind: "static",
        lexemeIds: itemsByGroup.get(group.id) ?? [],
      };
    }

    return {
      id: group.id,
      name: group.name,
      kind: "dynamic",
      filter: rulesByGroup.get(group.id) ?? { ...emptyDynamicStudyGroupFilter },
    };
  });

  const progress: VocabularyProgress = {};
  for (const row of progressRows) {
    progress[row.sense_id] = {
      attempts: Number(row.attempts),
      correct: Number(row.correct),
      incorrect: Number(row.incorrect),
      streak: Number(row.streak),
      lastPractisedAt: asIso(row.last_practised_at),
    };
  }

  return { groups: studyGroups, progress };
}

async function insertGroup(
  sql: postgres.TransactionSql,
  userId: string,
  group: StudyGroup,
  conflictMode: "merge" | "replace",
) {
  if (group.system) return;

  if (conflictMode === "replace") {
    await sql`
      insert into public.study_groups (user_id, id, name, kind, updated_at)
      values (${userId}, ${group.id}, ${group.name}, ${group.kind}, now())
    `;
  } else {
    await sql`
      insert into public.study_groups (user_id, id, name, kind, updated_at)
      values (${userId}, ${group.id}, ${group.name}, ${group.kind}, now())
      on conflict (user_id, id) do nothing
    `;
  }

  const [stored] = await sql<{ kind: "static" | "dynamic" }[]>`
    select kind from public.study_groups where user_id = ${userId} and id = ${group.id}
  `;
  if (!stored || stored.kind !== group.kind) return;

  if (group.kind === "static") {
    for (const senseId of Array.from(new Set(group.lexemeIds.filter(Boolean)))) {
      await sql`
        insert into public.study_group_items (user_id, group_id, sense_id)
        values (${userId}, ${group.id}, ${senseId})
        on conflict (user_id, group_id, sense_id) do nothing
      `;
    }
    return;
  }

  const rulesJson = JSON.stringify(group.filter);
  if (conflictMode === "replace") {
    await sql`
      insert into public.study_group_rules (user_id, group_id, rules, updated_at)
      values (${userId}, ${group.id}, ${rulesJson}::jsonb, now())
    `;
  } else {
    await sql`
      insert into public.study_group_rules (user_id, group_id, rules, updated_at)
      values (${userId}, ${group.id}, ${rulesJson}::jsonb, now())
      on conflict (user_id, group_id) do nothing
    `;
  }
}

export async function replaceStudyGroups(userId: string, groups: StudyGroup[]) {
  await ensureStudySchema();
  const sql = sqlClient();

  await sql.begin(async (tx) => {
    await tx`delete from public.study_groups where user_id = ${userId}`;
    for (const group of groups.filter((candidate) => !candidate.system)) {
      await insertGroup(tx, userId, group, "replace");
    }
  });
}

function saneProgress(record: VocabularyProgressRecord): VocabularyProgressRecord {
  const attempts = Math.max(0, Math.trunc(Number(record.attempts) || 0));
  const correct = Math.min(attempts, Math.max(0, Math.trunc(Number(record.correct) || 0)));
  const incorrect = Math.min(attempts, Math.max(0, Math.trunc(Number(record.incorrect) || 0)));
  return {
    attempts,
    correct,
    incorrect,
    streak: Math.max(0, Math.trunc(Number(record.streak) || 0)),
    lastPractisedAt: record.lastPractisedAt || "",
  };
}

export async function migrateLocalStudyState(
  userId: string,
  deviceId: string,
  groups: StudyGroup[],
  progress: VocabularyProgress,
) {
  await ensureStudySchema();
  const sql = sqlClient();
  const migrationKey = "local-storage-v1-to-cloud-v1";

  await sql.begin(async (tx) => {
    const [alreadyMigrated] = await tx<{ migrated_at: Date }[]>`
      select migrated_at
      from public.user_study_migrations
      where user_id = ${userId} and device_id = ${deviceId} and migration_key = ${migrationKey}
    `;

    if (alreadyMigrated) return;

    for (const group of groups.filter((candidate) => !candidate.system)) {
      await insertGroup(tx, userId, group, "merge");
    }

    for (const [senseId, rawRecord] of Object.entries(progress)) {
      if (!senseId) continue;
      const record = saneProgress(rawRecord);
      const lastPractisedAt = record.lastPractisedAt || null;
      await tx`
        insert into public.vocabulary_progress (
          user_id, sense_id, attempts, correct, incorrect, streak, last_practised_at, updated_at
        ) values (
          ${userId}, ${senseId}, ${record.attempts}, ${record.correct}, ${record.incorrect},
          ${record.streak}, ${lastPractisedAt}, now()
        )
        on conflict (user_id, sense_id) do update set
          attempts = greatest(public.vocabulary_progress.attempts, excluded.attempts),
          correct = greatest(public.vocabulary_progress.correct, excluded.correct),
          incorrect = greatest(public.vocabulary_progress.incorrect, excluded.incorrect),
          streak = greatest(public.vocabulary_progress.streak, excluded.streak),
          last_practised_at = greatest(public.vocabulary_progress.last_practised_at, excluded.last_practised_at),
          updated_at = now()
      `;
    }

    await tx`
      insert into public.user_study_migrations (user_id, device_id, migration_key)
      values (${userId}, ${deviceId}, ${migrationKey})
      on conflict (user_id, device_id, migration_key) do nothing
    `;
  });

  return getStudyState(userId);
}

export async function recordVocabularyAttempt(userId: string, input: StudyAttemptInput) {
  await ensureStudySchema();
  const sql = sqlClient();
  const difficulty = input.difficulty ?? null;
  const selectedAnswer = input.selectedAnswer ?? null;
  const correctIncrement = input.correct ? 1 : 0;
  const incorrectIncrement = input.correct ? 0 : 1;

  await sql.begin(async (tx) => {
    await tx`
      insert into public.vocabulary_attempts (
        user_id, sense_id, game_type, direction, difficulty, correct, selected_answer
      ) values (
        ${userId}, ${input.senseId}, ${input.gameType}, ${input.direction},
        ${difficulty}, ${input.correct}, ${selectedAnswer}
      )
    `;

    await tx`
      insert into public.vocabulary_progress (
        user_id, sense_id, attempts, correct, incorrect, streak, last_practised_at, updated_at
      ) values (
        ${userId}, ${input.senseId}, 1, ${correctIncrement}, ${incorrectIncrement},
        ${input.correct ? 1 : 0}, now(), now()
      )
      on conflict (user_id, sense_id) do update set
        attempts = public.vocabulary_progress.attempts + 1,
        correct = public.vocabulary_progress.correct + ${correctIncrement},
        incorrect = public.vocabulary_progress.incorrect + ${incorrectIncrement},
        streak = case
          when ${input.correct} then public.vocabulary_progress.streak + 1
          else 0
        end,
        last_practised_at = now(),
        updated_at = now()
    `;
  });
}
