import type { GrammarLevel } from "./types";

export type GrammarExerciseKind = "multiple-choice" | "gap" | "error-correction" | "transformation";

export type GrammarApplicationSeed = {
  conceptSlug: string;
  level: GrammarLevel;
  sectionHint?: string;
  kind: GrammarExerciseKind;
  prompt: string;
  explanation: string;
  skill: string;
  options?: string[];
  answerIndex?: number;
  acceptedAnswers?: string[];
  modelAnswer?: string;
  keyword?: string;
};

export const grammarApplicationSeeds: GrammarApplicationSeed[] = [
  {
    conceptSlug: "present-tenses",
    level: "B2",
    sectionHint: "Present simple",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the natural sentence for a permanent situation.",
    options: ["Maya is living in Bristol since 2019.", "Maya lives in Bristol.", "Maya has living in Bristol.", "Maya is live in Bristol."],
    answerIndex: 1,
    explanation: "Present simple describes stable or long-term situations.",
  },
  {
    conceptSlug: "present-tenses",
    level: "B2",
    sectionHint: "Present continuous",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: Prices ___ (rise) quickly at the moment.",
    acceptedAnswers: ["are rising"],
    modelAnswer: "are rising",
    explanation: "A developing change around now takes the present continuous.",
  },
  {
    conceptSlug: "present-tenses",
    level: "B2",
    sectionHint: "State verbs",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the best option: I ___ what you mean now.",
    options: ["am understanding", "understand", "have understanding", "understood now"],
    answerIndex: 1,
    explanation: "Understand is normally stative, so the simple form is used.",
  },
  {
    conceptSlug: "present-tenses",
    level: "B2",
    sectionHint: "The verb to be",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: Leo is being quiet in general.",
    acceptedAnswers: ["Leo is quiet in general", "Leo is quiet in general."],
    modelAnswer: "Leo is quiet in general.",
    explanation: "Be + being describes temporary behaviour, not a general characteristic.",
  },
  {
    conceptSlug: "present-tenses",
    level: "C1",
    sectionHint: "State verbs",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Which sentence uses think dynamically?",
    options: ["I think you're right.", "I'm thinking about moving abroad.", "I think this belongs to me.", "I think she knows."],
    answerIndex: 1,
    explanation: "Think is dynamic when it means consider/reflect on something.",
  },
  {
    conceptSlug: "perfect-continuous-aspect",
    level: "C1",
    sectionHint: "simple",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Which sentence focuses on the completed result?",
    options: ["I've been painting the kitchen.", "I've painted the kitchen.", "I'm painting the kitchen.", "I painted the kitchen every day."],
    answerIndex: 1,
    explanation: "The perfect simple highlights a completed result; the continuous highlights activity/process.",
  },
  {
    conceptSlug: "perfect-continuous-aspect",
    level: "C1",
    sectionHint: "continuous",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: Your hands are covered in flour. What ___ you ___ (bake)?",
    acceptedAnswers: ["have you been baking"],
    modelAnswer: "have you been baking",
    explanation: "Visible present evidence of a recent activity favours the present perfect continuous.",
  },
  {
    conceptSlug: "perfect-continuous-aspect",
    level: "C1",
    sectionHint: "unfinished",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the best option: This is the third time I ___ this week.",
    options: ["call", "have called", "have been called", "called"],
    answerIndex: 1,
    explanation: "A repeated event up to now in an unfinished time period uses present perfect.",
  },
  {
    conceptSlug: "perfect-continuous-aspect",
    level: "C1",
    sectionHint: "temporary",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I ___ (work) from the library this month because my office is being renovated.",
    acceptedAnswers: ["have been working"],
    modelAnswer: "have been working",
    explanation: "A temporary continuing situation up to the present is naturally expressed with the perfect continuous.",
  },
  {
    conceptSlug: "perfect-continuous-aspect",
    level: "C1",
    sectionHint: "stative",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: I've been knowing her for years.",
    acceptedAnswers: ["I've known her for years", "I've known her for years."],
    modelAnswer: "I've known her for years.",
    explanation: "Know is stative, so it normally does not appear in the continuous aspect.",
  },
  {
    conceptSlug: "past-tenses",
    level: "B2",
    sectionHint: "Past simple",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: We ___ (meet) at a conference last Thursday.",
    acceptedAnswers: ["met"],
    modelAnswer: "met",
    explanation: "A finished event at a specified past time takes past simple.",
  },
  {
    conceptSlug: "past-tenses",
    level: "B2",
    sectionHint: "Past continuous",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the best option: I ___ home when the storm started.",
    options: ["walked", "was walking", "had walked", "have walked"],
    answerIndex: 1,
    explanation: "Past continuous sets the background activity interrupted by a past-simple event.",
  },
  {
    conceptSlug: "past-tenses",
    level: "B2",
    sectionHint: "used to",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite with USED TO: I lived near the sea when I was a child, but I don't now.",
    acceptedAnswers: ["I used to live near the sea when I was a child", "I used to live near the sea when I was a child."],
    modelAnswer: "I used to live near the sea when I was a child.",
    keyword: "USED",
    explanation: "Used to can describe a past state that is no longer true.",
  },
  {
    conceptSlug: "past-tenses",
    level: "B2",
    sectionHint: "be used to",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: After six months, I'm finally ___ (work) night shifts.",
    acceptedAnswers: ["used to working"],
    modelAnswer: "used to working",
    explanation: "Be used to is followed by a noun or -ing form because to is a preposition.",
  },
  {
    conceptSlug: "past-tenses",
    level: "B2",
    sectionHint: "Past perfect simple",
    kind: "multiple-choice",
    skill: "application",
    prompt: "By the time the guests arrived, we ___ dinner.",
    options: ["finished", "had finished", "were finishing always", "have finished"],
    answerIndex: 1,
    explanation: "Past perfect marks an event completed before another past reference point.",
  },
  {
    conceptSlug: "past-tenses",
    level: "C1",
    sectionHint: "narrative",
    kind: "gap",
    skill: "gap",
    prompt: "Complete naturally: She ___ (drive) for hours when she finally found a petrol station.",
    acceptedAnswers: ["had been driving"],
    modelAnswer: "had been driving",
    explanation: "Past perfect continuous emphasises the duration of an activity leading up to a past moment.",
  },
  {
    conceptSlug: "future",
    level: "B2",
    sectionHint: "Present simple",
    kind: "multiple-choice",
    skill: "application",
    prompt: "The train ___ at 07:10 tomorrow.",
    options: ["will leaving", "leaves", "is leave", "has left"],
    answerIndex: 1,
    explanation: "Timetables and scheduled events commonly use present simple.",
  },
  {
    conceptSlug: "future",
    level: "B2",
    sectionHint: "Present continuous",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: We ___ (meet) the architect at three tomorrow; it's already arranged.",
    acceptedAnswers: ["are meeting"],
    modelAnswer: "are meeting",
    explanation: "A fixed personal arrangement uses present continuous.",
  },
  {
    conceptSlug: "future",
    level: "B2",
    sectionHint: "will",
    kind: "multiple-choice",
    skill: "application",
    prompt: "I think the new system ___ useful.",
    options: ["is being", "will be", "is going be", "has been"],
    answerIndex: 1,
    explanation: "Will is natural for a prediction based on opinion.",
  },
  {
    conceptSlug: "future",
    level: "B2",
    sectionHint: "going to",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Look at that shelf! It ___.",
    options: ["will collapse yesterday", "is going to collapse", "collapses every day", "has collapse"],
    answerIndex: 1,
    explanation: "Going to is used for a prediction based on present evidence.",
  },
  {
    conceptSlug: "future",
    level: "B2",
    sectionHint: "Future continuous",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: At this time tomorrow, I ___ (fly) to Dublin.",
    acceptedAnswers: ["will be flying"],
    modelAnswer: "will be flying",
    explanation: "Future continuous presents an activity in progress at a future time.",
  },
  {
    conceptSlug: "future",
    level: "B2",
    sectionHint: "Future perfect",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: By the end of June, they ___ (finish) the project.",
    acceptedAnswers: ["will have finished"],
    modelAnswer: "will have finished",
    explanation: "Future perfect looks back from a future deadline to a completed event.",
  },
  {
    conceptSlug: "future",
    level: "B2",
    sectionHint: "time",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: I'll phone you as soon as I will arrive.",
    acceptedAnswers: ["I'll phone you as soon as I arrive", "I'll phone you as soon as I arrive."],
    modelAnswer: "I'll phone you as soon as I arrive.",
    explanation: "After future time conjunctions such as as soon as, use a present form rather than will.",
  },
  {
    conceptSlug: "future",
    level: "C1",
    sectionHint: "future in the past",
    kind: "multiple-choice",
    skill: "application",
    prompt: "She said the lecture ___ in fifteen minutes, so we hurried.",
    options: ["was starting", "will start", "has started tomorrow", "starts yesterday"],
    answerIndex: 0,
    explanation: "Past continuous can describe a future event viewed from a past perspective.",
  },
  {
    conceptSlug: "future",
    level: "C1",
    sectionHint: "to have",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite to show an official plan that did not happen: The minister was scheduled to speak, but the event was cancelled.",
    acceptedAnswers: ["The minister was to have spoken, but the event was cancelled", "The minister was to have spoken but the event was cancelled"],
    modelAnswer: "The minister was to have spoken, but the event was cancelled.",
    explanation: "Was/were to have + past participle refers to an intended or arranged past event that did not happen.",
  },
  {
    conceptSlug: "questions",
    level: "B2",
    sectionHint: "Yes/no",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the correct question.",
    options: ["Did you went yesterday?", "Did you go yesterday?", "Went you yesterday?", "Do you went yesterday?"],
    answerIndex: 1,
    explanation: "After did, the main verb returns to the infinitive.",
  },
  {
    conceptSlug: "questions",
    level: "B2",
    sectionHint: "subject",
    kind: "gap",
    skill: "gap",
    prompt: "Complete the subject question: Who ___ the window? (break)",
    acceptedAnswers: ["broke"],
    modelAnswer: "broke",
    explanation: "A subject question does not use do/did support.",
  },
  {
    conceptSlug: "questions",
    level: "B2",
    sectionHint: "tags",
    kind: "gap",
    skill: "gap",
    prompt: "Complete the tag: You've met Sam before, ___?",
    acceptedAnswers: ["haven't you", "have you not"],
    modelAnswer: "haven't you",
    explanation: "A positive clause normally takes a negative question tag with the same auxiliary.",
  },
  {
    conceptSlug: "questions",
    level: "B2",
    sectionHint: "agreeing",
    kind: "multiple-choice",
    skill: "application",
    prompt: "I don't enjoy crowded places. — ___ do I.",
    options: ["So", "Neither", "Also", "Too"],
    answerIndex: 1,
    explanation: "Neither/Nor + auxiliary + subject agrees with a negative statement.",
  },
  {
    conceptSlug: "questions",
    level: "B2",
    sectionHint: "question words",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the question: Where you did buy it?",
    acceptedAnswers: ["Where did you buy it", "Where did you buy it?"],
    modelAnswer: "Where did you buy it?",
    explanation: "In an object question, the auxiliary comes before the subject: where did you buy...?",
  },
  {
    conceptSlug: "nouns-and-articles",
    level: "B2",
    sectionHint: "Countable",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the correct phrase.",
    options: ["an advice", "some advice", "two advices", "a furniture"],
    answerIndex: 1,
    explanation: "Advice is uncountable, so use some advice, not an advice.",
  },
  {
    conceptSlug: "nouns-and-articles",
    level: "B2",
    sectionHint: "article",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: ___ moon goes round the Earth.",
    acceptedAnswers: ["the", "The"],
    modelAnswer: "The",
    explanation: "The is used for a unique entity in the shared context.",
  },
  {
    conceptSlug: "nouns-and-articles",
    level: "B2",
    sectionHint: "no article",
    kind: "gap",
    skill: "gap",
    prompt: "Complete with an article or —: I listen to ___ music while I work.",
    acceptedAnswers: ["—", ""],
    modelAnswer: "—",
    explanation: "No article is used with an uncountable noun when speaking generally.",
  },
  {
    conceptSlug: "nouns-and-articles",
    level: "B2",
    sectionHint: "special",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: She goes to the school every weekday as a pupil.",
    acceptedAnswers: ["She goes to school every weekday as a pupil", "She goes to school every weekday as a pupil."],
    modelAnswer: "She goes to school every weekday as a pupil.",
    explanation: "With institutions used for their normal purpose, English often uses no article.",
  },
  {
    conceptSlug: "pronouns-and-determiners",
    level: "B2",
    sectionHint: "reflexive",
    kind: "multiple-choice",
    skill: "application",
    prompt: "They blamed ___ for the mistake.",
    options: ["them", "themselves", "their", "each"],
    answerIndex: 1,
    explanation: "Use a reflexive pronoun when subject and object refer to the same people.",
  },
  {
    conceptSlug: "pronouns-and-determiners",
    level: "B2",
    sectionHint: "there and it",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: ___ seems to be a problem with the heating.",
    acceptedAnswers: ["there", "There"],
    modelAnswer: "There",
    explanation: "There introduces the existence of something.",
  },
  {
    conceptSlug: "pronouns-and-determiners",
    level: "B2",
    sectionHint: "neither",
    kind: "multiple-choice",
    skill: "application",
    prompt: "___ of the two proposals is cheap enough.",
    options: ["None", "Neither", "No one", "Every"],
    answerIndex: 1,
    explanation: "Neither refers to not one and not the other of two.",
  },
  {
    conceptSlug: "pronouns-and-determiners",
    level: "B2",
    sectionHint: "each every",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: ___ student must submit an individual form.",
    acceptedAnswers: ["every", "each"],
    modelAnswer: "Every",
    explanation: "Every can refer to all members of a group individually; each is also possible in some contexts, so both are accepted where natural.",
  },
  {
    conceptSlug: "pronouns-and-determiners",
    level: "B2",
    sectionHint: "possessive",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: This coat is my, not yours.",
    acceptedAnswers: ["This coat is mine, not yours", "This coat is mine, not yours."],
    modelAnswer: "This coat is mine, not yours.",
    explanation: "A possessive pronoun such as mine stands alone; my must be followed by a noun.",
  },
  {
    conceptSlug: "introductory-it",
    level: "C1",
    sectionHint: "introductory subject",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite naturally: To solve the problem quickly is difficult.",
    acceptedAnswers: ["It is difficult to solve the problem quickly", "It's difficult to solve the problem quickly"],
    modelAnswer: "It is difficult to solve the problem quickly.",
    explanation: "Introductory it avoids a heavy infinitive clause as subject.",
  },
  {
    conceptSlug: "introductory-it",
    level: "C1",
    sectionHint: "cleft",
    kind: "gap",
    skill: "gap",
    prompt: "Complete the cleft: It was Maya ___ spotted the error first.",
    acceptedAnswers: ["who", "that"],
    modelAnswer: "who",
    explanation: "An it-cleft can focus a person with who/that.",
  },
  {
    conceptSlug: "introductory-it",
    level: "C1",
    sectionHint: "introductory object",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I find ___ difficult to concentrate with music on.",
    acceptedAnswers: ["it"],
    modelAnswer: "it",
    explanation: "Find + it + adjective + infinitive uses it as an introductory object.",
  },
  {
    conceptSlug: "introductory-it",
    level: "C1",
    sectionHint: "like",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I hate ___ when people speak over each other.",
    acceptedAnswers: ["it"],
    modelAnswer: "it",
    explanation: "Like/love/hate can use it before a following when-clause.",
  },
  {
    conceptSlug: "introductory-it",
    level: "C1",
    sectionHint: "introductory object",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: They made clear it that the deadline had changed.",
    acceptedAnswers: ["They made it clear that the deadline had changed", "They made it clear that the deadline had changed."],
    modelAnswer: "They made it clear that the deadline had changed.",
    explanation: "With make + introductory object, the order is make it + adjective + clause.",
  },
  {
    conceptSlug: "adjectives",
    level: "B2",
    sectionHint: "Comparative",
    kind: "multiple-choice",
    skill: "application",
    prompt: "This route is ___ than the motorway.",
    options: ["more short", "shorter", "shortest", "the shorter"],
    answerIndex: 1,
    explanation: "A short one-syllable adjective normally forms the comparative with -er.",
  },
  {
    conceptSlug: "adjectives",
    level: "B2",
    sectionHint: "-ed",
    kind: "multiple-choice",
    skill: "application",
    prompt: "I was really ___ by the ending.",
    options: ["surprising", "surprised", "surprise", "surprisingly person"],
    answerIndex: 1,
    explanation: "-ed adjectives commonly describe how a person feels.",
  },
  {
    conceptSlug: "adjectives",
    level: "B2",
    sectionHint: "order",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the natural order.",
    options: ["a wooden lovely old table", "a lovely old wooden table", "an old lovely wooden table", "a wooden old lovely table"],
    answerIndex: 1,
    explanation: "Opinion generally comes before age and material.",
  },
  {
    conceptSlug: "adjectives",
    level: "C1",
    sectionHint: "Intensifying",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: The second proposal is ___ clearer than the first. (far)",
    acceptedAnswers: ["far"],
    modelAnswer: "far",
    explanation: "Far can intensify a comparative.",
  },
  {
    conceptSlug: "adjectives",
    level: "C1",
    sectionHint: "As",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: The basic course is nowhere near ___ demanding as the intensive one.",
    acceptedAnswers: ["as"],
    modelAnswer: "as",
    explanation: "Nowhere near as ... as expresses a large distance from equality.",
  },
  {
    conceptSlug: "adjectives",
    level: "C1",
    sectionHint: "Like",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: Learning a language is as training a muscle.",
    acceptedAnswers: ["Learning a language is like training a muscle", "Learning a language is like training a muscle."],
    modelAnswer: "Learning a language is like training a muscle.",
    explanation: "Use like + noun/-ing for similarity; as is not a free substitute here.",
  },
  {
    conceptSlug: "adverbs",
    level: "B2",
    sectionHint: "forms",
    kind: "multiple-choice",
    skill: "application",
    prompt: "She explained the problem very ___.",
    options: ["clear", "clearly", "clearlier", "clearness"],
    answerIndex: 1,
    explanation: "An adverb modifies the way the action is performed.",
  },
  {
    conceptSlug: "adverbs",
    level: "B2",
    sectionHint: "hard",
    kind: "multiple-choice",
    skill: "application",
    prompt: "He works ___, but he ___ ever complains.",
    options: ["hard / hard", "hardly / hard", "hard / hardly", "hardly / hardly hard"],
    answerIndex: 2,
    explanation: "Hard = with effort; hardly = almost not.",
  },
  {
    conceptSlug: "adverbs",
    level: "B2",
    sectionHint: "position",
    kind: "gap",
    skill: "gap",
    prompt: "Complete naturally: She answered the question ___. (politely)",
    acceptedAnswers: ["politely"],
    modelAnswer: "politely",
    explanation: "A manner adverb naturally follows the object rather than splitting verb and object.",
  },
  {
    conceptSlug: "adverbs",
    level: "C1",
    sectionHint: "extreme",
    kind: "multiple-choice",
    skill: "application",
    prompt: "The room was ___ freezing.",
    options: ["absolutely", "slightly", "a bit", "fairly little"],
    answerIndex: 0,
    explanation: "Extreme/non-gradable adjectives such as freezing combine naturally with absolutely.",
  },
  {
    conceptSlug: "adverbs",
    level: "C1",
    sectionHint: "quite",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I'm ___ certain that this is the right address. (quite)",
    acceptedAnswers: ["quite"],
    modelAnswer: "quite",
    explanation: "Quite can intensify a non-gradable adjective, often with a meaning close to completely.",
  },
  {
    conceptSlug: "modals",
    level: "B2",
    sectionHint: "obligation",
    kind: "multiple-choice",
    skill: "application",
    prompt: "You ___ wear a seat belt. It's compulsory.",
    options: ["might", "must", "could", "would"],
    answerIndex: 1,
    explanation: "Must expresses strong obligation; have to can also express external obligation.",
  },
  {
    conceptSlug: "modals",
    level: "B2",
    sectionHint: "necessity",
    kind: "multiple-choice",
    skill: "application",
    prompt: "You ___ come tomorrow if you're busy; it's optional.",
    options: ["mustn't", "don't have to", "can't", "shouldn't"],
    answerIndex: 1,
    explanation: "Don't have to means there is no necessity; mustn't means prohibition.",
  },
  {
    conceptSlug: "modals",
    level: "B2",
    sectionHint: "advice",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: You ___ see a doctor if the pain continues.",
    acceptedAnswers: ["should", "ought to"],
    modelAnswer: "should",
    explanation: "Should/ought to are used for advice.",
  },
  {
    conceptSlug: "modals",
    level: "B2",
    sectionHint: "deduction",
    kind: "multiple-choice",
    skill: "application",
    prompt: "The lights are on and I can hear music. They ___ be home.",
    options: ["must", "can't", "shouldn't", "needn't"],
    answerIndex: 0,
    explanation: "Must expresses a strong positive deduction.",
  },
  {
    conceptSlug: "modals",
    level: "C1",
    sectionHint: "past possibility",
    kind: "multiple-choice",
    skill: "application",
    prompt: "She isn't answering. She ___ have left her phone at home.",
    options: ["might", "mustn't", "can't to", "should to"],
    answerIndex: 0,
    explanation: "Might/could/may + have + past participle express past possibility.",
  },
  {
    conceptSlug: "modals",
    level: "C1",
    sectionHint: "needn't have",
    kind: "multiple-choice",
    skill: "application",
    prompt: "We brought three umbrellas, but it stayed sunny. We ___.",
    options: ["didn't need bring them", "needn't have brought them", "mustn't bring them", "couldn't have bring them"],
    answerIndex: 1,
    explanation: "Needn't have + past participle means the action happened but turned out to be unnecessary.",
  },
  {
    conceptSlug: "modals",
    level: "C1",
    sectionHint: "ability",
    kind: "multiple-choice",
    skill: "application",
    prompt: "The door jammed, but after several attempts I ___ open it.",
    options: ["could", "was able to", "must", "would can"],
    answerIndex: 1,
    explanation: "For a successful specific past achievement, was/were able to is often preferred to could.",
  },
  {
    conceptSlug: "modals",
    level: "C1",
    sectionHint: "unfulfilled",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite using COULD HAVE: I had the ability to help, but I didn't.",
    acceptedAnswers: ["I could have helped", "I could have helped."],
    modelAnswer: "I could have helped.",
    keyword: "COULD",
    explanation: "Could have + past participle can express an unrealised past possibility/ability.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "B2",
    sectionHint: "-ing",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I avoid ___ (drive) in the city centre at rush hour.",
    acceptedAnswers: ["driving"],
    modelAnswer: "driving",
    explanation: "Avoid is followed by an -ing form.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "B2",
    sectionHint: "to-infinitive",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: We decided ___ (leave) early.",
    acceptedAnswers: ["to leave"],
    modelAnswer: "to leave",
    explanation: "Decide is followed by a to-infinitive.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "C1",
    sectionHint: "object",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: She persuaded me ___ (apply) for the post.",
    acceptedAnswers: ["to apply"],
    modelAnswer: "to apply",
    explanation: "Persuade follows the pattern verb + object + to-infinitive.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "C1",
    sectionHint: "bare",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: They made us ___ (wait) outside.",
    acceptedAnswers: ["wait"],
    modelAnswer: "wait",
    explanation: "Make + object takes the bare infinitive in the active.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "C1",
    sectionHint: "passive",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite in the passive: They made us wait outside.",
    acceptedAnswers: ["We were made to wait outside", "We were made to wait outside."],
    modelAnswer: "We were made to wait outside.",
    explanation: "In the passive, make is followed by a to-infinitive.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "C1",
    sectionHint: "remember",
    kind: "multiple-choice",
    skill: "application",
    prompt: "I remember ___ the door, so it can't be open.",
    options: ["to lock", "locking", "lock", "to locking"],
    answerIndex: 1,
    explanation: "Remember + -ing refers to a memory of an action that happened earlier.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "C1",
    sectionHint: "stop",
    kind: "multiple-choice",
    skill: "application",
    prompt: "He stopped ___ coffee because he wanted to sleep better.",
    options: ["to drink", "drinking", "drink", "to drinking"],
    answerIndex: 1,
    explanation: "Stop + -ing means cease an activity; stop + to-infinitive means pause another activity in order to do something.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "C1",
    sectionHint: "try",
    kind: "multiple-choice",
    skill: "application",
    prompt: "If the app freezes, try ___ it.",
    options: ["to restart only with intention", "restarting", "restart to", "having restart"],
    answerIndex: 1,
    explanation: "Try + -ing means experiment with a possible solution.",
  },
  {
    conceptSlug: "verb-patterns",
    level: "C1",
    sectionHint: "object -ing",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: I noticed him to leave the building.",
    acceptedAnswers: ["I noticed him leaving the building", "I noticed him leave the building", "I noticed him leaving the building."],
    modelAnswer: "I noticed him leaving the building.",
    explanation: "Notice can be followed by object + -ing (action in progress); a bare infinitive is also possible with a different viewpoint.",
  },
  {
    conceptSlug: "passive",
    level: "B2",
    sectionHint: "passive",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: The bridge ___ (build) in 1998.",
    acceptedAnswers: ["was built"],
    modelAnswer: "was built",
    explanation: "Past simple passive = was/were + past participle.",
  },
  {
    conceptSlug: "passive",
    level: "B2",
    sectionHint: "have/get",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I'm having my laptop ___ tomorrow. (repair)",
    acceptedAnswers: ["repaired"],
    modelAnswer: "repaired",
    explanation: "Have/get something done uses a past participle.",
  },
  {
    conceptSlug: "passive",
    level: "B2",
    sectionHint: "reporting",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite: People say that he is an excellent surgeon.",
    acceptedAnswers: ["He is said to be an excellent surgeon", "He is said to be an excellent surgeon."],
    modelAnswer: "He is said to be an excellent surgeon.",
    explanation: "Reporting passive: subject + be + past participle + to-infinitive.",
  },
  {
    conceptSlug: "passive",
    level: "C1",
    sectionHint: "forms",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Which sentence is a correct perfect passive?",
    options: ["The report has completed.", "The report has been completed.", "The report was been completed.", "The report has being completed."],
    answerIndex: 1,
    explanation: "Present perfect passive = has/have been + past participle.",
  },
  {
    conceptSlug: "passive",
    level: "C1",
    sectionHint: "impersonal",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite formally: People believe that the painting is genuine.",
    acceptedAnswers: ["It is believed that the painting is genuine", "It is believed that the painting is genuine."],
    modelAnswer: "It is believed that the painting is genuine.",
    explanation: "It + passive reporting verb + that-clause is a formal impersonal reporting structure.",
  },
  {
    conceptSlug: "passive",
    level: "C1",
    sectionHint: "agent",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct if necessary: The new policy was announced from the minister.",
    acceptedAnswers: ["The new policy was announced by the minister", "The new policy was announced by the minister."],
    modelAnswer: "The new policy was announced by the minister.",
    explanation: "By introduces the agent responsible for a passive action.",
  },
  {
    conceptSlug: "reported-speech",
    level: "B2",
    sectionHint: "tense",
    kind: "gap",
    skill: "gap",
    prompt: "Report: 'I'm exhausted.' → She said she ___ exhausted.",
    acceptedAnswers: ["was"],
    modelAnswer: "was",
    explanation: "With a past reporting verb, present often backshifts to past.",
  },
  {
    conceptSlug: "reported-speech",
    level: "B2",
    sectionHint: "questions",
    kind: "gap",
    skill: "gap",
    prompt: "Report: 'Where do you live?' → She asked me where I ___.",
    acceptedAnswers: ["lived"],
    modelAnswer: "lived",
    explanation: "Reported wh-questions use statement word order and normally backshift.",
  },
  {
    conceptSlug: "reported-speech",
    level: "B2",
    sectionHint: "commands",
    kind: "transformation",
    skill: "transformation",
    prompt: "Report: 'Don't touch it,' he told me.",
    acceptedAnswers: ["He told me not to touch it", "He told me not to touch it."],
    modelAnswer: "He told me not to touch it.",
    explanation: "Negative reported commands use tell + object + not to-infinitive.",
  },
  {
    conceptSlug: "reported-speech",
    level: "B2",
    sectionHint: "time",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Direct: 'I'll finish it tomorrow.' Reported the same day later: She said she would finish it ___.",
    options: ["the next day", "yesterday", "last week", "ago"],
    answerIndex: 0,
    explanation: "Tomorrow commonly changes to the next/following day in reported speech.",
  },
  {
    conceptSlug: "reported-speech",
    level: "C1",
    sectionHint: "verb pattern",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: She apologised ___ arriving late.",
    acceptedAnswers: ["for"],
    modelAnswer: "for",
    explanation: "Apologise for + -ing is one of the reporting-verb patterns.",
  },
  {
    conceptSlug: "reported-speech",
    level: "C1",
    sectionHint: "accuse",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: He accused me ___ taking his notes.",
    acceptedAnswers: ["of"],
    modelAnswer: "of",
    explanation: "Accuse somebody of + -ing.",
  },
  {
    conceptSlug: "reported-speech",
    level: "C1",
    sectionHint: "encourage",
    kind: "transformation",
    skill: "transformation",
    prompt: "Report: 'You should apply for the scholarship,' her tutor said.",
    acceptedAnswers: ["Her tutor encouraged her to apply for the scholarship", "Her tutor encouraged her to apply for the scholarship."],
    modelAnswer: "Her tutor encouraged her to apply for the scholarship.",
    explanation: "Encourage + object + to-infinitive reports advice/encouragement.",
  },
  {
    conceptSlug: "reported-speech",
    level: "C1",
    sectionHint: "impersonal",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite formally: People expect migration to increase.",
    acceptedAnswers: ["It is expected that migration will increase", "It is expected that migration will increase."],
    modelAnswer: "It is expected that migration will increase.",
    explanation: "An impersonal passive with it is common in formal reporting.",
  },
  {
    conceptSlug: "reported-speech",
    level: "C1",
    sectionHint: "reported questions",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: She asked me why had I left the job.",
    acceptedAnswers: ["She asked me why I had left the job", "She asked me why I had left the job."],
    modelAnswer: "She asked me why I had left the job.",
    explanation: "Reported questions use statement order: subject before auxiliary.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "Zero",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: If you heat ice, it ___.",
    acceptedAnswers: ["melts"],
    modelAnswer: "melts",
    explanation: "Zero conditional uses present + present for general truths.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "First",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: If I see Nina, I ___ her your message.",
    acceptedAnswers: ["will give", "'ll give"],
    modelAnswer: "will give",
    explanation: "First conditional uses a present form in the if-clause and a future/result form in the main clause.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "Second",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: If I had more time, I ___ more often.",
    acceptedAnswers: ["would travel", "'d travel"],
    modelAnswer: "would travel",
    explanation: "Second conditional expresses an unreal/unlikely present or future situation.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "Third",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: If we'd left earlier, we ___ the train.",
    acceptedAnswers: ["would have caught", "'d have caught"],
    modelAnswer: "would have caught",
    explanation: "Third conditional uses if + past perfect and would have + past participle.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "Mixed",
    kind: "multiple-choice",
    skill: "application",
    prompt: "If I had accepted that job, I ___ in Berlin now.",
    options: ["would live", "would be living", "will live", "lived"],
    answerIndex: 1,
    explanation: "A past unreal condition can have a present result: mixed conditional.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "unless",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I won't go ___ you come with me.",
    acceptedAnswers: ["unless"],
    modelAnswer: "unless",
    explanation: "Unless normally means if not.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "in case",
    kind: "gap",
    skill: "gap",
    prompt: "Take a charger ___ your battery runs out.",
    acceptedAnswers: ["in case"],
    modelAnswer: "in case",
    explanation: "In case expresses a precaution against a possible event.",
  },
  {
    conceptSlug: "conditionals",
    level: "B2",
    sectionHint: "wish",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I wish I ___ more free time now.",
    acceptedAnswers: ["had"],
    modelAnswer: "had",
    explanation: "Wish + past expresses dissatisfaction with a present situation.",
  },
  {
    conceptSlug: "conditionals",
    level: "C1",
    sectionHint: "past wish",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: I wish I ___ (not/say) that yesterday.",
    acceptedAnswers: ["hadn't said", "had not said"],
    modelAnswer: "hadn't said",
    explanation: "Wish + past perfect expresses regret about the past.",
  },
  {
    conceptSlug: "conditionals",
    level: "C1",
    sectionHint: "would rather",
    kind: "gap",
    skill: "gap",
    prompt: "I'd rather you ___ me before coming over.",
    acceptedAnswers: ["called"],
    modelAnswer: "called",
    explanation: "Would rather + different subject takes a past form for a present/future preference.",
  },
  {
    conceptSlug: "conditionals",
    level: "C1",
    sectionHint: "inversion",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite without if: If I had known, I would have called you.",
    acceptedAnswers: ["Had I known, I would have called you", "Had I known I would have called you"],
    modelAnswer: "Had I known, I would have called you.",
    explanation: "Formal conditional inversion removes if and places had before the subject.",
  },
  {
    conceptSlug: "conditionals",
    level: "C1",
    sectionHint: "were to",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: If the company ___ close tomorrow, hundreds of jobs would be affected.",
    acceptedAnswers: ["were to"],
    modelAnswer: "were to",
    explanation: "If + subject + were to + infinitive presents a remote hypothetical possibility.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "B2",
    sectionHint: "defining",
    kind: "gap",
    skill: "gap",
    prompt: "The woman ___ lives next door is a surgeon.",
    acceptedAnswers: ["who", "that"],
    modelAnswer: "who",
    explanation: "A defining relative clause about a person can use who/that as subject.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "B2",
    sectionHint: "object",
    kind: "gap",
    skill: "gap",
    prompt: "Complete with an optional relative pronoun or —: This is the book ___ I told you about.",
    acceptedAnswers: ["—", "that", "which"],
    modelAnswer: "—",
    explanation: "An object relative pronoun can be omitted in a defining clause.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "B2",
    sectionHint: "non-defining",
    kind: "multiple-choice",
    skill: "application",
    prompt: "My sister, ___ lives in Cork, is visiting tomorrow.",
    options: ["that", "who", "—", "what"],
    answerIndex: 1,
    explanation: "Non-defining clauses use who/which, not that, and the pronoun cannot be omitted.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "B2",
    sectionHint: "whose",
    kind: "gap",
    skill: "gap",
    prompt: "The student ___ laptop was stolen reported it immediately.",
    acceptedAnswers: ["whose"],
    modelAnswer: "whose",
    explanation: "Whose expresses possession.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "B2",
    sectionHint: "preposition",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the more formal version.",
    options: ["The colleague I spoke to was helpful.", "The colleague to whom I spoke was helpful.", "The colleague to that I spoke was helpful.", "The colleague whom I spoke to him was helpful."],
    answerIndex: 1,
    explanation: "A preposition can come before whom/which in formal style.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "C1",
    sectionHint: "whole clause",
    kind: "gap",
    skill: "gap",
    prompt: "He missed the final train, ___ meant he had to take a taxi.",
    acceptedAnswers: ["which"],
    modelAnswer: "which",
    explanation: "Non-defining which can refer to the whole preceding clause.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "C1",
    sectionHint: "whoever",
    kind: "gap",
    skill: "gap",
    prompt: "___ finishes first can leave early.",
    acceptedAnswers: ["whoever", "Whoever"],
    modelAnswer: "Whoever",
    explanation: "Whoever can introduce a free relative meaning 'the person who, no matter who'.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "C1",
    sectionHint: "whatever",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Choose the meaning of 'Whatever you decide, I'll support you.'",
    options: ["Only one specific decision is allowed.", "It doesn't matter what you decide.", "You must not decide.", "The decision happened in the past."],
    answerIndex: 1,
    explanation: "Whatever can mean 'no matter what'.",
  },
  {
    conceptSlug: "relative-clauses",
    level: "C1",
    sectionHint: "participle",
    kind: "transformation",
    skill: "transformation",
    prompt: "Reduce the relative clause: The people who live above us are moving out.",
    acceptedAnswers: ["The people living above us are moving out", "The people living above us are moving out."],
    modelAnswer: "The people living above us are moving out.",
    explanation: "An active defining relative clause can often be reduced to an -ing participle clause.",
  },
  {
    conceptSlug: "prepositions",
    level: "B2",
    sectionHint: "time",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: The meeting starts ___ six o'clock.",
    acceptedAnswers: ["at"],
    modelAnswer: "at",
    explanation: "At is used for a specific clock time.",
  },
  {
    conceptSlug: "prepositions",
    level: "B2",
    sectionHint: "time",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: The report must be ready ___ Friday at the latest.",
    acceptedAnswers: ["by"],
    modelAnswer: "by",
    explanation: "By means no later than the stated time.",
  },
  {
    conceptSlug: "prepositions",
    level: "B2",
    sectionHint: "place",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: She hid ___ the bed.",
    acceptedAnswers: ["under", "beneath"],
    modelAnswer: "under",
    explanation: "Under describes a lower position, often directly beneath something.",
  },
  {
    conceptSlug: "prepositions",
    level: "B2",
    sectionHint: "verbs",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: It depends ___ the weather.",
    acceptedAnswers: ["on"],
    modelAnswer: "on",
    explanation: "Depend on is a fixed verb + preposition combination.",
  },
  {
    conceptSlug: "prepositions",
    level: "B2",
    sectionHint: "adjectives",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: She's very good ___ languages.",
    acceptedAnswers: ["at"],
    modelAnswer: "at",
    explanation: "Good at is a fixed adjective + preposition combination.",
  },
  {
    conceptSlug: "prepositions",
    level: "B2",
    sectionHint: "duration",
    kind: "error-correction",
    skill: "error-correction",
    prompt: "Correct the sentence: I stayed there during three days.",
    acceptedAnswers: ["I stayed there for three days", "I stayed there for three days."],
    modelAnswer: "I stayed there for three days.",
    explanation: "For expresses duration; during is followed by an event/period noun, not a measured duration in this pattern.",
  },
  {
    conceptSlug: "linking-words",
    level: "B2",
    sectionHint: "because",
    kind: "multiple-choice",
    skill: "application",
    prompt: "We stayed inside ___ the weather was awful.",
    options: ["because", "therefore", "despite", "so that"],
    answerIndex: 0,
    explanation: "Because introduces a reason clause.",
  },
  {
    conceptSlug: "linking-words",
    level: "B2",
    sectionHint: "therefore",
    kind: "gap",
    skill: "gap",
    prompt: "The roads were flooded; ___, the match was cancelled.",
    acceptedAnswers: ["therefore"],
    modelAnswer: "therefore",
    explanation: "Therefore is a linking adverb expressing result.",
  },
  {
    conceptSlug: "linking-words",
    level: "B2",
    sectionHint: "purpose",
    kind: "gap",
    skill: "gap",
    prompt: "I left early ___ catch the first train.",
    acceptedAnswers: ["to", "in order to"],
    modelAnswer: "to",
    explanation: "To/in order to + infinitive expresses purpose.",
  },
  {
    conceptSlug: "linking-words",
    level: "B2",
    sectionHint: "so such",
    kind: "multiple-choice",
    skill: "application",
    prompt: "It was ___ a difficult test that several students ran out of time.",
    options: ["so", "such", "too", "enough"],
    answerIndex: 1,
    explanation: "Such + a/an + adjective + noun + that.",
  },
  {
    conceptSlug: "linking-words",
    level: "B2",
    sectionHint: "despite",
    kind: "gap",
    skill: "gap",
    prompt: "___ being tired, she finished the report.",
    acceptedAnswers: ["despite", "in spite of"],
    modelAnswer: "Despite",
    explanation: "Despite/in spite of can be followed by an -ing form.",
  },
  {
    conceptSlug: "linking-words",
    level: "B2",
    sectionHint: "even though",
    kind: "multiple-choice",
    skill: "application",
    prompt: "___ he was exhausted, he kept working.",
    options: ["Even though", "Despite of", "Because of he", "Therefore"],
    answerIndex: 0,
    explanation: "Even though introduces a concessive clause.",
  },
  {
    conceptSlug: "linking-words",
    level: "C1",
    sectionHint: "conjunctions",
    kind: "gap",
    skill: "gap",
    prompt: "I'll help you ___ you tell me exactly what happened. (provided that)",
    acceptedAnswers: ["provided that", "provided"],
    modelAnswer: "provided that",
    explanation: "Provided (that) can introduce a condition.",
  },
  {
    conceptSlug: "cohesion",
    level: "C1",
    sectionHint: "substitution",
    kind: "multiple-choice",
    skill: "application",
    prompt: "I ordered the vegetarian option, and Maya did ___ too.",
    options: ["so", "it one", "that one did", "such"],
    answerIndex: 0,
    explanation: "Do so can substitute for a previously mentioned verb phrase.",
  },
  {
    conceptSlug: "cohesion",
    level: "C1",
    sectionHint: "ellipsis",
    kind: "gap",
    skill: "gap",
    prompt: "I can attend the morning session, but I don't know if Sam ___.",
    acceptedAnswers: ["can"],
    modelAnswer: "can",
    explanation: "Ellipsis avoids repeating a recoverable verb phrase after an auxiliary.",
  },
  {
    conceptSlug: "cohesion",
    level: "C1",
    sectionHint: "reference",
    kind: "multiple-choice",
    skill: "application",
    prompt: "In 'Maya bought a new laptop. She uses it for work', what creates grammatical cohesion?",
    options: ["Reference with she/it", "A comparative", "A passive", "An inversion"],
    answerIndex: 0,
    explanation: "Pronouns refer back to earlier nouns and create reference cohesion.",
  },
  {
    conceptSlug: "cohesion",
    level: "C1",
    sectionHint: "linking adverbials",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Which linker adds another supporting point?",
    options: ["Moreover", "Nevertheless", "Consequently", "On the contrary"],
    answerIndex: 0,
    explanation: "Moreover/furthermore add information.",
  },
  {
    conceptSlug: "cohesion",
    level: "C1",
    sectionHint: "result",
    kind: "gap",
    skill: "gap",
    prompt: "The evidence was incomplete. ___, the committee postponed its decision.",
    acceptedAnswers: ["Consequently", "As a result"],
    modelAnswer: "Consequently",
    explanation: "Consequently/as a result link a cause to its result.",
  },
  {
    conceptSlug: "cohesion",
    level: "C1",
    sectionHint: "contrast",
    kind: "multiple-choice",
    skill: "application",
    prompt: "The first plan is expensive. ___, the alternative is much slower.",
    options: ["On the other hand", "Consequently", "Moreover only", "For this reason"],
    answerIndex: 0,
    explanation: "On the other hand introduces a contrasting consideration.",
  },
  {
    conceptSlug: "inversion",
    level: "C1",
    sectionHint: "negative",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite with NEVER: I had never seen such a crowded station.",
    acceptedAnswers: ["Never had I seen such a crowded station", "Never had I seen such a crowded station."],
    modelAnswer: "Never had I seen such a crowded station.",
    keyword: "NEVER",
    explanation: "A negative adverbial at the front triggers auxiliary-subject inversion.",
  },
  {
    conceptSlug: "inversion",
    level: "C1",
    sectionHint: "hardly",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: Hardly ___ we arrived when the fire alarm went off.",
    acceptedAnswers: ["had"],
    modelAnswer: "had",
    explanation: "Hardly + past perfect inversion is followed by when.",
  },
  {
    conceptSlug: "inversion",
    level: "C1",
    sectionHint: "no sooner",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: No sooner ___ she sat down than the phone rang.",
    acceptedAnswers: ["had"],
    modelAnswer: "had",
    explanation: "No sooner + past perfect inversion typically pairs with than.",
  },
  {
    conceptSlug: "inversion",
    level: "C1",
    sectionHint: "not until",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite with NOT UNTIL: I didn't understand the problem until she explained it.",
    acceptedAnswers: ["Not until she explained it did I understand the problem", "Not until she explained it did I understand the problem."],
    modelAnswer: "Not until she explained it did I understand the problem.",
    keyword: "NOT UNTIL",
    explanation: "With not until fronted, inversion occurs in the main clause.",
  },
  {
    conceptSlug: "inversion",
    level: "C1",
    sectionHint: "only when",
    kind: "transformation",
    skill: "transformation",
    prompt: "Rewrite with ONLY WHEN: I realised how serious it was when I saw the figures.",
    acceptedAnswers: ["Only when I saw the figures did I realise how serious it was", "Only when I saw the figures did I realise how serious it was."],
    modelAnswer: "Only when I saw the figures did I realise how serious it was.",
    keyword: "ONLY WHEN",
    explanation: "Only + adverbial at the front triggers inversion in the main clause.",
  },
  {
    conceptSlug: "inversion",
    level: "C1",
    sectionHint: "not only",
    kind: "gap",
    skill: "gap",
    prompt: "Complete: Not only ___ he apologise, but he also offered a refund.",
    acceptedAnswers: ["did"],
    modelAnswer: "did",
    explanation: "Not only at the front triggers auxiliary-subject inversion.",
  },
  {
    conceptSlug: "inversion",
    level: "C1",
    sectionHint: "register",
    kind: "multiple-choice",
    skill: "application",
    prompt: "Which sentence has the formal/literary inversion taught at C1?",
    options: ["I rarely have seen such confusion.", "Rarely have I seen such confusion.", "Rarely I have seen such confusion.", "I have rarely did see such confusion."],
    answerIndex: 1,
    explanation: "Fronted negative/restrictive adverbials trigger inversion: Rarely have I seen...",
  },
];
